<?php
/**
 * Research landing copy for every store compound.
 * Scientific sections follow the .com overview pages. Sequences follow the theme amino diagrams.
 *
 * @package PalmBeachVitality
 */

if (!defined('ABSPATH')) {
    exit;
}

/**
 * @return array<string,array<string,mixed>>
 */
function pbv_research_catalog() {
    return array(
        '5-amino-1mq' => array(
            'kicker' => 'Metabolic',
            'category' => 'Metabolic',
            'title' => '5-Amino-1MQ',
            'subtitle' => 'NNMT Inhibitor',
            'sequence_note' => 'Small molecule, not a peptide: 5-amino-1-methylquinolinium',
            'kind' => 'molecule',
            'overview' => '5-Amino-1MQ is a quinolinium small molecule studied as an inhibitor of nicotinamide N-methyltransferase (NNMT). It is not a peptide. Laboratory work examines how blocking NNMT changes nicotinamide methylation and related metabolic readouts in cell and animal models.',
            'mechanism' => 'NNMT methylates nicotinamide and consumes cellular methyl donor. Inhibitor studies, including work that names 5-amino-1-methylquinolinium, follow that enzyme in adipose and other metabolic models. Findings stay preclinical relative to a settled human mechanism.',
            'uses' => array(
                'NNMT enzyme inhibition assays',
                'Nicotinamide methylation and NAD-related pathway research',
                'Adipocyte and whole-animal metabolic models',
                'Analytical methods for the quinolinium inhibitor',
            ),
            'notations' => array(
                'Case-study notation (preclinical): papers that name 5-amino-1-methylquinolinium examine NNMT inhibition in metabolic models.',
                'Case-study notation (analytical): a plasma assay paper describes pharmacokinetic measurement of this quinolinium compound in rats.',
                'This catalog page does not present clinical outcome claims. Human interventional evidence specific to this molecule remains limited.',
            ),
            'related' => array(
                'AOD-9604',
                'MOTS-c',
            ),
            'tokens' => array(),
        ),
        'aod-9604' => array(
            'kicker' => 'Metabolic',
            'category' => 'Metabolic',
            'title' => 'AOD-9604',
            'subtitle' => 'hGH Fragment 176–191 Analog',
            'sequence_note' => 'Tyr-hGH(176–191) lipolytic domain analog (AOD9604)',
            'kind' => 'linear',
            'overview' => 'AOD-9604 is a synthetic peptide corresponding to the C-terminal lipolytic domain of human growth hormone (fragment 176–191), studied for fat-metabolism effects without classical GH growth activity.',
            'mechanism' => 'Investigated for β3-adrenergic–related lipolytic signaling and adipose metabolic regulation distinct from full-length GH IGF-1 growth pathways.',
            'uses' => array(
                'Adipose lipid-metabolism assays',
                'Obesity pharmacology screening',
                'Cartilage/OA intra-articular exploratory models',
                'Anti-doping detection method development',
            ),
            'notations' => array(
                'Case-study notation: early metabolic studies in obese mouse models evaluated lipid metabolism after chronic AOD9604 exposure.',
                'Case-study notation: rabbit osteoarthritis work explored intra-articular AOD9604 ± hyaluronic acid.',
                'Human efficacy evidence is more limited than for GLP-1 class agents; emphasize preclinical framing.',
            ),
            'related' => array(
                'Semaglutide',
                'Tirzepatide',
                'Retatrutide',
            ),
            'tokens' => array(
                'Y',
                'L',
                'R',
                'I',
                'V',
                'Q',
                'C',
                'R',
                'S',
                'V',
                'E',
                'G',
                'S',
                'C',
                'G',
                'F',
            ),
        ),
        'bpc-157' => array(
            'kicker' => 'Growth Factors',
            'category' => 'Growth Factors',
            'title' => 'BPC-157',
            'subtitle' => 'Body Protection Compound-157',
            'sequence_note' => 'Pentadecapeptide (15 aa): GEPPPGKPADDAGLV',
            'kind' => 'linear',
            'overview' => 'BPC-157 is a synthetic 15–amino-acid fragment derived from a protective protein sequence found in human gastric juice. In laboratory models it is studied for effects on soft-tissue repair pathways, angiogenesis, and gastrointestinal mucosal integrity.',
            'mechanism' => 'Preclinical work suggests BPC-157 may influence nitric-oxide signaling, growth-factor pathways (including VEGFR2-related angiogenesis), and tendon/muscle fibroblast activity. Most mechanistic data remain preclinical.',
            'uses' => array(
                'Tendon and ligament healing models (transection and crush injury designs)',
                'Skeletal-muscle repair and functional recovery studies',
                'Gastrointestinal ulcer and fistula healing models',
                'Vascular and angiogenesis pathway research',
            ),
            'notations' => array(
                'Case-study notation (preclinical): transected Achilles tendon models have reported faster collagen organization versus controls when BPC-157 was administered systemically or locally.',
                'Case-study notation (preclinical): muscle crush designs have associated BPC-157 with improved functional recovery markers and angiogenesis-related histology.',
                'Clinical translation remains limited; published human interventional evidence is sparse compared with animal literature.',
            ),
            'related' => array(
                'TB-500',
                'GHK-Cu',
            ),
            'tokens' => array(
                'G',
                'E',
                'P',
                'P',
                'P',
                'G',
                'K',
                'P',
                'A',
                'D',
                'D',
                'A',
                'G',
                'L',
                'V',
            ),
        ),
        'cagrilintide' => array(
            'kicker' => 'Metabolic',
            'category' => 'Metabolic',
            'title' => 'Cagrilintide',
            'subtitle' => 'Long-Acting Amylin Analog',
            'sequence_note' => 'C20 diacid–γ-Glu–KCNTATCATQRLAEFLRHSSNNFGPILPPTNVGSNTP. Disulfide Cys2–Cys7.',
            'kind' => 'linear',
            'overview' => 'Cagrilintide is a lipidated analog of amylin, a pancreatic peptide involved in satiety signaling. Published work describes it as a long-acting amylin analog for receptor and metabolic research.',
            'mechanism' => 'Amylin signals through calcitonin-receptor complexes with receptor-activity-modifying proteins. Research on cagrilintide focuses on that pharmacology and on how a prolonged amylin-receptor agonist behaves in experimental models.',
            'uses' => array(
                'Amylin-receptor pharmacology',
                'Satiety and energy-balance signaling models',
                'Comparison with other metabolic peptide analogs',
                'Analytical identity of lipidated amylin analogs',
            ),
            'notations' => array(
                'Case-study notation: development papers describe cagrilintide as a long-acting amylin analogue.',
                'Case-study notation: later reviews place it in the amylin-receptor literature alongside other metabolic peptide research.',
                'This page summarizes research context. It does not state clinical outcome claims.',
            ),
            'related' => array(
                'Semaglutide',
                'AOD-9604',
            ),
            'tokens' => array(
                'Ac',
                'K',
                'C',
                'N',
                'T',
                'A',
                'T',
                'C',
                'A',
                'T',
                'Q',
                'R',
                'L',
                'A',
                'N',
                'F',
                'L',
                'V',
                'H',
                'S',
                'S',
                'N',
                'N',
                'F',
                'G',
                'P',
                'I',
                'L',
                'P',
                'P',
                'T',
                'N',
                'V',
                'G',
                'S',
                'N',
                'T',
                'Y',
            ),
        ),
        'cjc-1295' => array(
            'kicker' => 'Hormonal',
            'category' => 'Hormonal',
            'title' => 'CJC-1295 (DAC)',
            'subtitle' => 'Long-Acting GHRH Analog',
            'sequence_note' => 'GHRH(1–29)-based analog; DAC constructs add Drug Affinity Complex albumin-binding chemistry',
            'kind' => 'linear',
            'overview' => 'CJC-1295 is a long-acting growth hormone–releasing hormone (GHRH) analog designed for prolonged GH and IGF-1 elevation via albumin binding (DAC versions).',
            'mechanism' => 'Stimulates pituitary GHRH receptors; DAC chemistry extends half-life, producing multi-day GH/IGF-1 elevation in human pharmacokinetic studies.',
            'uses' => array(
                'Long-acting GHRH pharmacology',
                'GH/IGF-1 axis kinetics',
                'Serum proteome response to sustained GH drive',
                'Anti-doping detection of GHRH analogs',
            ),
            'notations' => array(
                'Case-study notation: clinical pharmacology papers showed prolonged GH and IGF-1 secretion after CJC-1295.',
                'Case-study notation: once-daily dosing studies quantified enhanced GH/IGF-1 profiles versus shorter GHRH fragments.',
                'Specify DAC vs non-DAC material in documentation—half-life differs substantially.',
            ),
            'related' => array(
                'Ipamorelin',
                'Tesamorelin',
            ),
            'tokens' => array(
                'Y',
                'A',
                'D',
                'A',
                'I',
                'F',
                'T',
                'Q',
                'S',
                'Y',
                'R',
                'K',
                'V',
                'L',
                'A',
                'Q',
                'L',
                'S',
                'A',
                'R',
                'K',
                'L',
                'L',
                'Q',
                'D',
                'I',
                'L',
                'S',
                'R',
            ),
        ),
        'cjc-ipamorelin' => array(
            'kicker' => 'Stacks',
            'category' => 'Stacks',
            'title' => 'CJC/Ipamorelin',
            'subtitle' => 'CJC + Ipamorelin',
            'sequence_note' => 'Combo display: CJC no DAC YADAIFTQSYRKVLAQLSARKLLQDILSR · Ipamorelin',
            'kind' => 'stack',
            'overview' => 'CJC/Ipamorelin is a two-peptide research stack: the short-acting CJC GHRH analog (not CJC-1295 with Drug Affinity Complex) plus ipamorelin, a selective growth-hormone secretagogue. Each component has its own literature. This page does not claim a single pivotal trial of the fixed combination.',
            'mechanism' => 'CJC-class peptides are studied at the GHRH receptor. Ipamorelin is studied as a ghrelin-receptor agonist with selective GH release in preclinical work. Combination use is a research design that engages both pathways.',
            'uses' => array(
                'Combined GHRH-receptor and ghrelin-receptor models',
                'Growth-hormone axis co-stimulation studies',
                'Comparison with either component alone',
                'Identity testing of two-peptide preparations',
            ),
            'notations' => array(
                'Case-study notation: ipamorelin papers describe a selective growth-hormone secretagogue, separate from GHRH analogs.',
                'Case-study notation: CJC-1295 pharmacokinetic trials describe the DAC analog and are not studies of this stack.',
                'Read the CJC and Ipamorelin pages for the single-compound identities.',
            ),
            'related' => array(
                'CJC',
                'Ipamorelin',
            ),
            'tokens' => array(),
        ),
        'dsip' => array(
            'kicker' => 'Cognitive',
            'category' => 'Cognitive',
            'title' => 'DSIP',
            'subtitle' => 'Delta Sleep-Inducing Peptide',
            'sequence_note' => 'Nonapeptide (9 aa): WAGGDASGE',
            'kind' => 'linear',
            'overview' => 'DSIP (delta sleep-inducing peptide) is a short neuropeptide first discussed in sleep research. Reviews describe proposed links to sleep architecture and stress-axis signaling, and they emphasize that the mechanism is still unsettled.',
            'mechanism' => 'DSIP is studied as a neuropeptide candidate rather than a fully mapped receptor system. Commentary in the literature treats receptor identity, active sequence, and downstream signaling as open questions.',
            'uses' => array(
                'Sleep-architecture research models',
                'Neuropeptide signaling assays',
                'Circadian and stress-axis exploratory studies',
                'Analytical characterization of the peptide',
            ),
            'notations' => array(
                'Case-study notation: early reviews summarize DSIP as a candidate neuropeptide in sleep research.',
                'Case-study notation: later commentary still describes the peptide as mechanistically unresolved.',
                'Human interventional literature is sparse relative to descriptive and preclinical discussion.',
            ),
            'related' => array(
                'Semax',
                'Selank',
            ),
            'tokens' => array(
                'W',
                'A',
                'G',
                'G',
                'D',
                'A',
                'S',
                'G',
                'E',
            ),
        ),
        'ghk-cu' => array(
            'kicker' => 'Growth Factors',
            'category' => 'Growth Factors',
            'title' => 'GHK-Cu',
            'subtitle' => 'Copper Tripeptide (Gly-His-Lys·Cu²⁺)',
            'sequence_note' => 'Tripeptide GHK complexed with copper(II)',
            'kind' => 'linear',
            'overview' => 'GHK-Cu is a naturally occurring copper-binding tripeptide studied for extracellular-matrix remodeling, antioxidant gene programs, and skin/wound biology.',
            'mechanism' => 'GHK chelates Cu²⁺ and is reported to modulate metalloproteinases, collagen/elastin-related gene expression, and anti-inflammatory transcriptional programs in skin and soft tissue models.',
            'uses' => array(
                'Dermal regeneration and cosmetic-peptide research',
                'Wound-healing and scar-remodeling assays',
                'Hair follicle and scalp biology models',
                'Gene-expression studies of copper-peptide signaling',
            ),
            'notations' => array(
                'Case-study notation: Pickart and colleagues documented GHK-associated tissue remodeling and gene resetting signatures in skin-aging contexts.',
                'Case-study notation: copper-tripeptide complexes have been evaluated for attenuating inflammatory and fibrotic responses in lung injury models.',
                'Formulation stability of the Cu²⁺ complex is an important analytical QC variable.',
            ),
            'related' => array(
                'BPC-157',
                'TB-500',
            ),
            'tokens' => array(
                'G',
                'H',
                'K',
            ),
        ),
        'glow' => array(
            'kicker' => 'Stacks',
            'category' => 'Stacks',
            'title' => 'GLOW Stack',
            'subtitle' => 'BPC-157 + TB-500 + GHK-Cu',
            'sequence_note' => 'Combo display: GHK · BPC-157 · TB-500 motif',
            'kind' => 'stack',
            'overview' => 'GLOW combines matrix-remodeling copper-tripeptide biology (GHK-Cu) with BPC-157 and Tβ4-fragment research themes for skin/soft-tissue regeneration study designs.',
            'mechanism' => 'Targets overlapping ECM remodeling, angiogenesis, and cell-migration pathways described independently for each component.',
            'uses' => array(
                'Skin regeneration multi-peptide assays',
                'Dermal wound models with combination arms',
                'Gene-expression panels spanning GHK and repair peptides',
                'Cosmetic-research ingredient characterization',
            ),
            'notations' => array(
                'Case-study notation: GHK remodeling/anti-aging papers anchor the skin-facing rationale.',
                'Case-study notation: BPC-157 wound and Tβ4 regenerative literature support soft-tissue endpoints.',
                'Avoid implying a single landmark trial for the branded stack name.',
            ),
            'related' => array(
                'Wolverine',
                'KLOW',
            ),
            'tokens' => array(),
        ),
        'ipamorelin' => array(
            'kicker' => 'Hormonal',
            'category' => 'Hormonal',
            'title' => 'Ipamorelin',
            'subtitle' => 'Selective Growth Hormone Secretagogue',
            'sequence_note' => 'Pentapeptide GHS: Aib-His-D-2-Nal-D-Phe-Lys-NH₂',
            'kind' => 'linear',
            'overview' => 'Ipamorelin is a selective ghrelin-receptor (GHS-R1a) agonist developed as a growth-hormone secretagogue with reduced ACTH/cortisol off-target activity relative to earlier GHRPs.',
            'mechanism' => 'Binds GHS-R1a to stimulate pituitary GH release in a pulse-compatible manner; studied for nitrogen balance, bone, and GI motility endpoints in animals.',
            'uses' => array(
                'Selective GH secretagogue pharmacology',
                'Postoperative ileus rodent models',
                'Bone mineral / longitudinal growth studies',
                'GH axis biomarker panels',
            ),
            'notations' => array(
                'Case-study notation: foundational papers describe ipamorelin as the first highly selective GH secretagogue.',
                'Case-study notation: rodent postoperative ileus work evaluated ghrelin-mimetic motility effects.',
                'Differentiate research peptide lots from pharmaceutical secretagogue development compounds.',
            ),
            'related' => array(
                'CJC-1295 (DAC)',
                'Tesamorelin',
            ),
            'tokens' => array(
                'Aib',
                'H',
                'D-2',
                'D-P',
                'K',
            ),
        ),
        'klow' => array(
            'kicker' => 'Stacks',
            'category' => 'Stacks',
            'title' => 'KLOW Stack',
            'subtitle' => 'KPV + BPC-157 + TB-500 + GHK-Cu',
            'sequence_note' => 'Combo schematic: KPV · GHK · BPC-157 · TB-500 components',
            'kind' => 'stack',
            'overview' => 'KLOW is a four-component research stack combining anti-inflammatory KPV signaling with BPC-157, Tβ4-fragment, and GHK-Cu pathways for multi-axis inflammation and repair studies.',
            'mechanism' => 'Intended experimental rationale: melanocortin-fragment inflammation control + tissue-repair peptides + copper-tripeptide matrix remodeling.',
            'uses' => array(
                'Multi-pathway inflammation/repair screens',
                'Gut–skin axis exploratory designs',
                'Component contribution knockout-style comparisons',
                'Complex kit analytical method development',
            ),
            'notations' => array(
                'Case-study notation: KPV intestinal-inflammation uptake studies motivate the immune/gut arm.',
                'Case-study notation: remaining endpoints rely on component BPC-157, Tβ4, and GHK literature.',
                'Clearly label each vial/peptide in multi-component kits for research traceability.',
            ),
            'related' => array(
                'Wolverine',
                'GLOW',
            ),
            'tokens' => array(),
        ),
        'kpv' => array(
            'kicker' => 'Immune',
            'category' => 'Immune',
            'title' => 'KPV',
            'subtitle' => 'α-MSH C-Terminal Tripeptide',
            'sequence_note' => 'Lys-Pro-Val (α-MSH 11–13)',
            'kind' => 'linear',
            'overview' => 'KPV is the C-terminal tripeptide of α-melanocyte–stimulating hormone, studied for anti-inflammatory and barrier-protective effects, including PepT1-mediated intestinal uptake.',
            'mechanism' => 'Melanocortin-related anti-inflammatory signaling with evidence for reduced NF-κB–linked cytokine programs; intestinal transport via PepT1 is a distinctive research feature.',
            'uses' => array(
                'Intestinal inflammation and colitis models',
                'Cutaneous inflammation / wound immunomodulation',
                'Melanocortin peptide structure–activity studies',
                'Peptide transporter (PepT1) research',
            ),
            'notations' => array(
                'Case-study notation: PepT1-mediated KPV uptake was linked to reduced intestinal inflammation in experimental models.',
                'Case-study notation: classic α-MSH fragment work dissected anti-inflammatory contributions of the KPV motif.',
                'Tripeptide identity testing is straightforward by MS but formulation stability still matters.',
            ),
            'related' => array(
                'NAD+',
            ),
            'tokens' => array(
                'K',
                'P',
                'V',
            ),
        ),
        'melanotan' => array(
            'kicker' => 'Hormonal',
            'category' => 'Hormonal',
            'title' => 'Melanotan II',
            'subtitle' => 'Melanocortin Receptor Agonist',
            'sequence_note' => 'Cyclic lactam: Ac-Nle-cyclo[Asp-His-D-Phe-Arg-Trp-Lys]-NH2',
            'kind' => 'cyclic',
            'overview' => 'Melanotan II is a synthetic cyclic peptide that binds melanocortin receptors in pharmacological research. This page covers receptor and laboratory signaling literature.',
            'mechanism' => 'The cyclic lactam is studied for melanocortin-receptor affinity, including MC4R-related pathways. Published animal work examines central melanocortin signaling, feeding behavior, and thermogenic models.',
            'uses' => array(
                'Melanocortin receptor binding assays',
                'MC4R signaling models',
                'Central neuropeptide pharmacology',
                'Chemical comparison with related cyclic peptides',
            ),
            'notations' => array(
                'Case-study notation (preclinical): melanotan II has been used as a melanocortin agonist in feeding and thermogenesis models.',
                'Case-study notation: chemistry papers describe staple and scaffold work that uses the melanotan II sequence as a substrate.',
                'This page does not describe cosmetic outcomes. Receptor binding is not an appearance claim.',
            ),
            'related' => array(
                'PT-141',
                'Kisspeptin',
            ),
            'tokens' => array(
                'Ac',
                'Nle',
                'D',
                'H',
                'dF',
                'R',
                'W',
                'K',
                'NH2',
            ),
        ),
        'mots-c' => array(
            'kicker' => 'Mitochondrial',
            'category' => 'Mitochondrial',
            'title' => 'MOTS-c',
            'subtitle' => 'Mitochondrial-Derived Peptide',
            'sequence_note' => 'Mitochondrial peptide (16 aa): MRWQEMGYIFYPRKLR',
            'kind' => 'linear',
            'overview' => 'MOTS-c is a peptide encoded in mitochondrial 12S rRNA. Research examines its proposed roles in metabolic homeostasis, muscle and fat metabolism, and mitochondrial-nuclear communication.',
            'mechanism' => 'Preclinical studies explore AMPK-related metabolic signaling and cellular responses to metabolic stress. Human evidence is earlier-stage than the cell and animal literature.',
            'uses' => array(
                'Mitochondrial-derived peptide assays',
                'Metabolic homeostasis models',
                'Cellular stress-signaling studies',
                'Comparison with other mitochondrial peptides',
            ),
            'notations' => array(
                'Case-study notation (preclinical): the original description linked MOTS-c to metabolic homeostasis in cell and mouse models.',
                'Case-study notation: later reviews discuss MOTS-c as a mitochondrial-derived peptide with metabolic research interest.',
                'This page does not present clinical outcome claims.',
            ),
            'related' => array(
                'SS-31',
                'AOD-9604',
            ),
            'tokens' => array(
                'M',
                'R',
                'W',
                'Q',
                'E',
                'M',
                'G',
                'Y',
                'I',
                'F',
                'Y',
                'P',
                'R',
                'K',
                'L',
                'R',
            ),
        ),
        'nad' => array(
            'kicker' => 'Mitochondrial',
            'category' => 'Mitochondrial',
            'title' => 'NAD+',
            'subtitle' => 'Nicotinamide Adenine Dinucleotide',
            'sequence_note' => 'Not a peptide — dinucleotide coenzyme (nicotinamide + ribose + ADP-ribose). Diagram shows modular units.',
            'kind' => 'molecule',
            'overview' => 'NAD+ is a central redox coenzyme. Research interest focuses on NAD+-boosting strategies (e.g., nicotinamide riboside, NMN) for aging biology, mitochondrial function, and metabolic resilience.',
            'mechanism' => 'Supports sirtuin and PARP enzymatic activity; precursor supplementation can raise blood and tissue NAD+ metabolomes in human studies.',
            'uses' => array(
                'NAD+ metabolome quantification',
                'Aging and senescence pathway research',
                'Skeletal-muscle bioenergetics studies',
                'Safety/tolerability of NAD precursors in humans',
            ),
            'notations' => array(
                'Case-study notation: chronic nicotinamide riboside raised NAD+ in healthy middle-aged/older adults with good tolerability.',
                'Case-study notation: aged skeletal-muscle studies show NR can augment the NAD+ metabolome.',
                'NAD+ itself differs from peptide APIs—handle analytical methods accordingly.',
            ),
            'related' => array(
                'KPV',
                'Glutathione',
            ),
            'tokens' => array(),
            'diagram' => true,
        ),
        'pt-141' => array(
            'kicker' => 'Hormonal',
            'category' => 'Hormonal',
            'title' => 'PT-141',
            'subtitle' => 'Bremelanotide, Melanocortin Agonist',
            'sequence_note' => 'Cyclic lactam: Ac-Nle-cyclo[Asp-His-D-Phe-Arg-Trp-Lys]-OH',
            'kind' => 'cyclic',
            'overview' => 'PT-141, also called bremelanotide, is a cyclic peptide in the melanocortin agonist family, chemically related to melanotan research sequences. Indexed literature discusses it as a melanocortin-receptor ligand.',
            'mechanism' => 'Pharmacology papers describe melanocortin-receptor agonism with a profile distinct from linear alpha-MSH fragments. This catalog page stays with receptor research and does not state clinical outcome claims.',
            'uses' => array(
                'Melanocortin receptor pharmacology',
                'Cyclic peptide structure-activity research',
                'Central melanocortin signaling models',
                'Analytical comparison with related melanocortin peptides',
            ),
            'notations' => array(
                'Case-study notation: drug-monograph and approval literature indexes bremelanotide as a melanocortin agonist.',
                'Case-study notation: safety summaries across the clinical development program are published separately from receptor-assay papers.',
                'Related melanotan II is a different cyclic melanocortin peptide. The two are not the same material.',
            ),
            'related' => array(
                'Melanotan II',
                'Kisspeptin',
            ),
            'tokens' => array(
                'Ac',
                'Nle',
                'D',
                'H',
                'dF',
                'R',
                'W',
                'K',
            ),
        ),
        'retatrutide' => array(
            'kicker' => 'Metabolic',
            'category' => 'Metabolic',
            'title' => 'Retatrutide',
            'subtitle' => 'Triple Agonist (GLP-1 / GIP / Glucagon)',
            'sequence_note' => 'Investigational triple agonist scaffold (retatrutide / LY3437943 class); X denotes Aib-like substitution in display',
            'kind' => 'linear',
            'overview' => 'Retatrutide is an investigational triple hormone-receptor agonist (GLP-1, GIP, and glucagon receptors) evaluated in phase 2 obesity and metabolic liver-disease programs.',
            'mechanism' => 'Combines incretin receptor agonism with glucagon-receptor activity hypothesized to increase energy expenditure while reducing caloric intake.',
            'uses' => array(
                'Next-generation incretin/glucagon pharmacology',
                'Obesity phase-2 translational research context',
                'Metabolic dysfunction–associated steatotic liver disease (MASLD) studies',
                'Comparative multi-agonist receptor profiling',
            ),
            'notations' => array(
                'Case-study notation: a phase 2 NEJM trial reported dose-dependent weight reduction with retatrutide in adults with obesity.',
                'Case-study notation: subsequent analyses explore MASLD and related cardiometabolic comorbidities.',
                'Compound remains investigational; cite primary trial publications rather than marketing claims.',
            ),
            'related' => array(
                'Semaglutide',
                'Tirzepatide',
                'AOD-9604',
            ),
            'tokens' => array(
                'Y',
                'X',
                'E',
                'G',
                'T',
                'F',
                'T',
                'S',
                'D',
                'Y',
                'S',
                'I',
                'L',
                'L',
                'D',
                'K',
                'K',
                'A',
                'A',
                'Q',
                'A',
                'F',
                'I',
                'E',
                'Y',
                'L',
                'L',
                'E',
                'G',
                'G',
                'P',
                'S',
                'S',
                'G',
                'A',
                'P',
                'P',
                'P',
                'S',
            ),
        ),
        'selank' => array(
            'kicker' => 'Cognitive',
            'category' => 'Cognitive',
            'title' => 'Selank',
            'subtitle' => 'Tuftsin Analog Heptapeptide',
            'sequence_note' => 'Thr-Lys-Pro-Arg-Pro-Gly-Pro (synthetic tuftsin analog)',
            'kind' => 'linear',
            'overview' => 'Selank is a synthetic tuftsin analog investigated for anxiolytic-like and immunomodulatory properties in behavioral and molecular neuroscience research.',
            'mechanism' => 'Tuftsin-family peptides intersect immune and CNS signaling; Selank studies examine gene-expression changes, stress-related behavior, and memory paradigms.',
            'uses' => array(
                'Anxiety and adaptive-behavior models',
                'Alcohol/opioid withdrawal experimental paradigms',
                'Functional connectomics with Semax comparators',
                'Immunopeptide signaling research',
            ),
            'notations' => array(
                'Case-study notation: rodent studies report attenuation of aversive morphine-withdrawal signs with Selank.',
                'Case-study notation: ethanol-related memory impairment models have tested Selank for protective behavioral effects.',
                'Keep claims tied to cited experimental systems; avoid clinical treatment language.',
            ),
            'related' => array(
                'Semax',
            ),
            'tokens' => array(
                'T',
                'K',
                'P',
                'R',
                'P',
                'G',
                'P',
            ),
        ),
        'semaglutide' => array(
            'kicker' => 'Metabolic',
            'category' => 'Metabolic',
            'title' => 'Semaglutide',
            'subtitle' => 'GLP-1 Receptor Agonist',
            'sequence_note' => 'GLP-1(7–37)-based backbone with Aib8 substitution and Lys26 fatty-acid acylation (commercial semaglutide chemistry)',
            'kind' => 'linear',
            'overview' => 'Semaglutide is a long-acting GLP-1 receptor agonist extensively studied in metabolic disease for glycemic control, body-weight reduction, and cardiovascular outcomes.',
            'mechanism' => 'Activates GLP-1 receptors to enhance glucose-dependent insulin secretion, suppress glucagon, slow gastric emptying, and reduce appetite via central and peripheral pathways.',
            'uses' => array(
                'Type 2 diabetes metabolic pathway research',
                'Obesity and energy-balance model systems',
                'Cardiovascular outcome biology (STEP/SELECT/SUSTAIN programs)',
                'Incretin receptor pharmacology comparisons',
            ),
            'notations' => array(
                'Case-study notation (clinical program): STEP trials reported substantial mean weight reduction with once-weekly semaglutide 2.4 mg versus placebo in adults with overweight/obesity.',
                'Case-study notation (clinical program): SUSTAIN-6 and SELECT evaluated cardiovascular outcomes in diabetes and obesity populations, respectively.',
                'Research materials should be handled as RUO and not represented as dispensed drug product.',
            ),
            'related' => array(
                'Tirzepatide',
                'Retatrutide',
                'AOD-9604',
            ),
            'tokens' => array(
                'H',
                'A',
                'E',
                'G',
                'T',
                'F',
                'T',
                'S',
                'D',
                'V',
                'S',
                'S',
                'Y',
                'L',
                'E',
                'G',
                'Q',
                'A',
                'A',
                'K',
                'E',
                'F',
                'I',
                'A',
                'W',
                'L',
                'V',
                'R',
                'G',
                'R',
                'G',
            ),
        ),
        'semax' => array(
            'kicker' => 'Cognitive',
            'category' => 'Cognitive',
            'title' => 'Semax',
            'subtitle' => 'ACTH(4–10) Heptapeptide Analog',
            'sequence_note' => 'Met-Glu-His-Phe-Pro-Gly-Pro (ACTH4–10 analog)',
            'kind' => 'linear',
            'overview' => 'Semax is a synthetic ACTH(4–10) analog studied primarily in neurobiology for effects on cognition-related pathways, neurotrophin expression, and neuroprotection models.',
            'mechanism' => 'Reported to modulate BDNF/trkB transcription and monoaminergic systems in rodent CNS models; copper-binding properties have also been characterized.',
            'uses' => array(
                'Neurotrophin gene-expression studies',
                'Cognitive and behavioral neuroscience models',
                'Ischemia/neuroprotection experimental systems',
                'Peptide–metal (copper) interaction chemistry',
            ),
            'notations' => array(
                'Case-study notation: hippocampal BDNF/trkB upregulation has been reported after Semax administration in rodent designs.',
                'Case-study notation: ischemia models have linked Semax/related glyprolines to neurotrophin pathway activation.',
                'Most Semax literature is preclinical or regional clinical research; interpret external validity cautiously.',
            ),
            'related' => array(
                'Selank',
            ),
            'tokens' => array(
                'M',
                'E',
                'H',
                'F',
                'P',
                'G',
                'P',
            ),
        ),
        'sermorelin' => array(
            'kicker' => 'Hormonal',
            'category' => 'Hormonal',
            'title' => 'Sermorelin',
            'subtitle' => 'GHRH(1–29) Analog',
            'sequence_note' => 'GHRH(1–29) (29 aa): YADAIFTNSYRKVLGQLSARKLLQDIMSR',
            'kind' => 'linear',
            'overview' => 'Sermorelin is a synthetic peptide corresponding to the first 29 amino acids of growth hormone–releasing hormone. It is studied as a GHRH-receptor agonist in growth-hormone axis research.',
            'mechanism' => 'It stimulates pituitary GHRH receptors and is used in research on GH secretion. It is distinct from CJC-1295 with Drug Affinity Complex, which is the long-acting analog on a separate catalog page.',
            'uses' => array(
                'GHRH receptor pharmacology',
                'Growth-hormone axis stimulation models',
                'Comparison with longer-acting GHRH analogs',
                'Analytical identification of GHRH(1–29) sequences',
            ),
            'notations' => array(
                'Case-study notation: reviews describe sermorelin as the 1–29 fragment of GHRH used in endocrine research.',
                'Case-study notation: investigators should separate this fragment from albumin-binding CJC-1295, which has different exposure.',
                'This page does not present clinical outcome claims.',
            ),
            'related' => array(
                'CJC-1295 (DAC)',
                'Tesamorelin',
            ),
            'tokens' => array(
                'Y',
                'A',
                'D',
                'A',
                'I',
                'F',
                'T',
                'N',
                'S',
                'Y',
                'R',
                'K',
                'V',
                'L',
                'G',
                'Q',
                'L',
                'S',
                'A',
                'R',
                'K',
                'L',
                'L',
                'Q',
                'D',
                'I',
                'M',
                'S',
                'R',
            ),
        ),
        'ss-31' => array(
            'kicker' => 'Mitochondrial',
            'category' => 'Mitochondrial',
            'title' => 'SS-31',
            'subtitle' => 'Mitochondria-Targeted Tetrapeptide',
            'sequence_note' => 'D-Arg–dimethylTyr–Lys–Phe. D-Arg and dimethyltyrosine are marked as modified.',
            'kind' => 'linear',
            'overview' => 'SS-31, also called elamipretide, is a synthetic tetrapeptide studied for association with cardiolipin in the inner mitochondrial membrane. It is a mitochondria-targeted research peptide, not a growth-hormone analog.',
            'mechanism' => 'Reviews describe membrane binding, effects on mitochondrial readouts, and use in cellular stress models. Mechanism papers focus on the inner membrane rather than on endocrine receptors.',
            'uses' => array(
                'Mitochondrial membrane assays',
                'Cardiolipin-interaction studies',
                'Cellular stress models involving mitochondria',
                'Comparison with other mitochondria-targeted peptides',
            ),
            'notations' => array(
                'Case-study notation: reviews summarize elamipretide structure and proposed mitochondrial mechanism.',
                'Case-study notation (preclinical): cell and mouse papers examine SS-31 in mitochondrial stress models.',
                'MOTS-c is a different mitochondrial peptide. The two sequences are not interchangeable.',
            ),
            'related' => array(
                'MOTS-c',
                'NAD+',
            ),
            'tokens' => array(
                'dR',
                'Dmt',
                'K',
                'F',
                'NH2',
            ),
        ),
        'ta-1' => array(
            'kicker' => 'Immune',
            'category' => 'Immune',
            'title' => 'TA-1',
            'subtitle' => 'Thymosin Alpha-1',
            'sequence_note' => 'N-acetyl thymosin α1 (28 aa): SDAAVDTSSEITTKDLKEKKEVVEEAEN',
            'kind' => 'linear',
            'overview' => 'Thymosin alpha-1 (TA-1) is a 28–amino-acid thymic peptide. Reviews examine its activity in innate and adaptive immune-cell models and summarize a large clinical literature without this page restating outcome claims.',
            'mechanism' => 'Laboratory work explores T-cell and dendritic-cell related signaling. It is a thymic immune peptide, distinct from thymosin beta-4 fragments such as TB-500.',
            'uses' => array(
                'Immune-cell signaling assays',
                'Thymic peptide characterization',
                'Innate and adaptive immunity models',
                'Analytical confirmation of the thymosin alpha-1 sequence',
            ),
            'notations' => array(
                'Case-study notation: narrative reviews summarize thymosin alpha-1 as a thymic immune peptide.',
                'Case-study notation: later reviews compile human clinical-trial literature under research and medical headings.',
                'TB-500 is a different thymosin fragment. Sequence identity should be confirmed on the certificate of analysis.',
            ),
            'related' => array(
                'KPV',
                'NAD+',
            ),
            'tokens' => array(
                'S',
                'D',
                'A',
                'A',
                'V',
                'D',
                'T',
                'S',
                'S',
                'E',
                'I',
                'T',
                'T',
                'K',
                'D',
                'L',
                'K',
                'E',
                'K',
                'K',
                'E',
                'V',
                'V',
                'E',
                'E',
                'A',
                'E',
                'N',
            ),
        ),
        'tb-500' => array(
            'kicker' => 'Growth Factors',
            'category' => 'Growth Factors',
            'title' => 'TB-500',
            'subtitle' => 'Thymosin Beta-4 Fragment (LKKTETQ motif)',
            'sequence_note' => 'Active-site fragment commonly associated with TB-500 research: Ac-LKKTETQ (derived from thymosin β4)',
            'kind' => 'linear',
            'overview' => 'TB-500 refers to a research fragment centered on the actin-binding motif of thymosin β4 (Tβ4). Full-length Tβ4 is a 43–amino-acid peptide that sequesters G-actin and participates in cell migration and tissue remodeling pathways.',
            'mechanism' => 'Thymosin β4 regulates actin polymerization, cell motility, and regenerative signaling. The LKKTETQ motif is a key actin-binding region studied for wound and soft-tissue repair biology.',
            'uses' => array(
                'Actin dynamics and cell-migration assays',
                'Wound-healing and dermal repair models',
                'Cardiac and neurological injury research using Tβ4 biology',
                'Comparative studies of Tβ4 fragments versus full-length peptide',
            ),
            'notations' => array(
                'Case-study notation: regenerative reviews summarize Tβ4 activity across dermal, ocular, and cardiac injury models, emphasizing actin-mediated cell migration.',
                'Case-study notation: neurological injury literature explores Tβ4 as a restorative peptide candidate in stroke and neurodegeneration models.',
                'Commercial “TB-500” preparations should be analytically distinguished from full-length thymosin β4.',
            ),
            'related' => array(
                'BPC-157',
                'GHK-Cu',
            ),
            'tokens' => array(
                'L',
                'K',
                'K',
                'T',
                'E',
                'T',
                'Q',
            ),
        ),
        'tesamorelin' => array(
            'kicker' => 'Hormonal',
            'category' => 'Hormonal',
            'title' => 'Tesamorelin',
            'subtitle' => 'Stabilized GHRH(1–44) Analog',
            'sequence_note' => 'Trans-3-hexenoyl-GHRH(1–44)-NH₂ analog class (tesamorelin scaffold display)',
            'kind' => 'linear',
            'overview' => 'Tesamorelin is a stabilized GHRH analog studied and used clinically for reduction of excess visceral adipose tissue in HIV-associated lipodystrophy, with additional metabolic and hepatic-fat research.',
            'mechanism' => 'Pulsatile GH release via GHRH receptor activation; visceral fat and liver-fat endpoints have been primary clinical research readouts.',
            'uses' => array(
                'Visceral adiposity and body-composition research',
                'HIV lipodystrophy metabolic models',
                'Liver-fat / NAFLD-adjacent imaging endpoints',
                'GH axis therapeutics pharmacology',
            ),
            'notations' => array(
                'Case-study notation: randomized studies reported reductions in visceral and liver fat in HIV patients with abdominal fat accumulation.',
                'Case-study notation: newer work examines tesamorelin with modern antiretroviral regimens and neurocognitive outcomes.',
                'Present research-grade material separately from approved branded drug product.',
            ),
            'related' => array(
                'Ipamorelin',
                'CJC-1295 (DAC)',
            ),
            'tokens' => array(
                'Y',
                'A',
                'D',
                'A',
                'I',
                'F',
                'T',
                'N',
                'S',
                'Y',
                'R',
                'K',
                'V',
                'L',
                'G',
                'Q',
                'L',
                'S',
                'A',
                'R',
                'K',
                'L',
                'L',
                'Q',
                'D',
                'I',
                'M',
                'S',
                'R',
                'Q',
                'Q',
                'G',
                'E',
                'S',
                'N',
                'Q',
                'E',
                'R',
                'G',
                'A',
                'R',
                'A',
                'R',
                'L',
            ),
        ),
        'tesamorelin-ipamorelin' => array(
            'kicker' => 'Stacks',
            'category' => 'Stacks',
            'title' => 'Tesamorelin/Ipamorelin',
            'subtitle' => 'Tesamorelin + Ipamorelin',
            'sequence_note' => 'Combo display: tesamorelin scaffold · Ipamorelin Aib-His-D-2-Nal-D-Phe-Lys',
            'kind' => 'stack',
            'overview' => 'Tesamorelin/Ipamorelin is a two-peptide research stack: tesamorelin, a growth hormone–releasing hormone analog, plus ipamorelin, a growth-hormone secretagogue. Component papers are published separately more often than as a fixed combination. This page does not claim a single pivotal trial of the pair.',
            'mechanism' => 'Tesamorelin is studied at the GHRH receptor. Ipamorelin is studied at the ghrelin receptor. Overlapping research interest is GH-axis pharmacology, with each ligand documented on its own.',
            'uses' => array(
                'Combined GHRH-receptor and ghrelin-receptor models',
                'Growth-hormone axis co-stimulation studies',
                'Comparison with tesamorelin or ipamorelin alone',
                'Identity testing of two-peptide preparations',
            ),
            'notations' => array(
                'Case-study notation: tesamorelin reviews describe a GHRH analog with its own pharmacokinetic literature.',
                'Case-study notation: ipamorelin is a selective GH secretagogue and a different receptor class.',
                'Read the Tesamorelin and Ipamorelin pages for the single-compound identities.',
            ),
            'related' => array(
                'Tesamorelin',
                'Ipamorelin',
            ),
            'tokens' => array(),
        ),
        'tirzepatide' => array(
            'kicker' => 'Metabolic',
            'category' => 'Metabolic',
            'title' => 'Tirzepatide',
            'subtitle' => 'Dual GIP/GLP-1 Receptor Agonist',
            'sequence_note' => '39–residue dual agonist peptide with fatty-acid modification (tirzepatide scaffold; X denotes Aib)',
            'kind' => 'linear',
            'overview' => 'Tirzepatide is a dual glucose-dependent insulinotropic polypeptide (GIP) and GLP-1 receptor agonist studied for type 2 diabetes and obesity.',
            'mechanism' => 'Simultaneous GIP and GLP-1 receptor engagement amplifies incretin signaling relevant to insulin secretion, appetite regulation, and adipose/energy metabolism.',
            'uses' => array(
                'Dual-incretin receptor pharmacology',
                'Obesity intervention model comparisons (SURMOUNT)',
                'Head-to-head incretin agonist studies (SURPASS vs semaglutide)',
                'Metabolic syndrome biomarker panels',
            ),
            'notations' => array(
                'Case-study notation: SURPASS-2 compared tirzepatide with semaglutide for glycemic endpoints in type 2 diabetes.',
                'Case-study notation: SURMOUNT-1 evaluated once-weekly tirzepatide for obesity treatment endpoints.',
                'Dual-agonist design requires careful peptide identity testing (MS/HPLC).',
            ),
            'related' => array(
                'Semaglutide',
                'Retatrutide',
                'AOD-9604',
            ),
            'tokens' => array(
                'Y',
                'X',
                'E',
                'G',
                'T',
                'F',
                'T',
                'S',
                'D',
                'Y',
                'S',
                'I',
                'A',
                'L',
                'D',
                'K',
                'I',
                'A',
                'Q',
                'K',
                'A',
                'F',
                'V',
                'Q',
                'W',
                'L',
                'I',
                'A',
                'G',
                'G',
                'P',
                'S',
                'S',
                'G',
                'A',
                'P',
                'P',
                'P',
                'S',
            ),
        ),
        'wolverine' => array(
            'kicker' => 'Stacks',
            'category' => 'Stacks',
            'title' => 'Wolverine Stack',
            'subtitle' => 'BPC-157 + TB-500',
            'sequence_note' => 'Combo display: BPC-157 sequence · TB-500/LKKTETQ motif',
            'kind' => 'stack',
            'overview' => 'Wolverine is a research stack pairing BPC-157 with a thymosin-β4–related fragment (TB-500 motif) to interrogate complementary soft-tissue repair and actin-migration pathways.',
            'mechanism' => 'Combines angiogenesis/tissue-protection hypotheses from BPC-157 literature with actin-cytoskeleton motility biology from Tβ4 research.',
            'uses' => array(
                'Multi-peptide recovery model designs',
                'Comparative monotherapy vs combination histology',
                'Tendon–muscle co-injury paradigms',
                'Analytical differentiation of dual-peptide kits',
            ),
            'notations' => array(
                'Case-study notation: cite component literature separately—combination kits rarely have dedicated RCTs.',
                'Case-study notation: BPC-157 tendon/muscle papers + Tβ4 regenerative reviews form the scientific backbone.',
                'QC should confirm both peptide identities and ratios in the kit.',
            ),
            'related' => array(
                'GLOW',
                'KLOW',
            ),
            'tokens' => array(),
        ),
        'dihexa' => array(
            'kicker' => 'Cognitive',
            'category' => 'Cognitive',
            'title' => 'Dihexa',
            'subtitle' => 'Angiotensin IV–Derived Peptide',
            'sequence_note' => 'N-hexanoyl–Tyr–Ile–aminohexanamide. A capped dipeptide, not an open chain.',
            'kind' => 'linear',
            'chip' => 'Capped analog',
            'diagram' => true,
            'overview' => 'Dihexa is N-hexanoic-Tyr-Ile-(6) aminohexanoic amide, a capped analog developed from angiotensin IV research. Laboratory papers examine it in synaptic and cognitive models.',
            'mechanism' => 'Preclinical reports have described synaptogenic effects and a proposed link to HGF/c-Met. The main 2014 paper for that HGF/c-Met claim was later retracted, and the 2013 characterization paper carries a notice of concern, so the mechanism is not settled.',
            'uses' => array(
                'HGF/c-Met signaling assays',
                'Synaptogenesis models',
                'Cognitive-research pathway studies in laboratory animals',
                'Comparison with other angiotensin IV–related peptides',
            ),
            'notations' => array(
                'Case-study notation: the 2013 characterization of this capped analog carries a journal notice of concern.',
                'Case-study notation: a 2014 paper tying angiotensin IV–derived peptides to HGF/c-Met was later retracted.',
                'Later animal papers still examine dihexa in cognitive-impairment and nerve-repair models. This page does not present clinical outcome claims.',
            ),
            'related' => array(
                'Semax',
                'Selank',
            ),
            'tokens' => array(),
        ),
        'epithalon' => array(
            'kicker' => 'Hormonal',
            'category' => 'Hormonal',
            'title' => 'Epithalon',
            'subtitle' => 'Pineal Tetrapeptide',
            'sequence_note' => 'Tetrapeptide (4 aa): AEDG',
            'kind' => 'linear',
            'diagram' => true,
            'overview' => 'Epithalon (also spelled epitalon) is a synthetic tetrapeptide based on a pineal peptide sequence. Cell and animal literature examines telomerase activity, telomere readouts, and pineal-peptide biology.',
            'mechanism' => 'In vitro studies report telomerase-related effects and changes in telomere-length assays. The peptide is studied as a short pineal sequence, not as a growth-hormone secretagogue.',
            'uses' => array(
                'Telomerase and telomere assays in cell models',
                'Pineal peptide research',
                'Comparative studies of short peptide sequences',
                'In vitro aging-model readouts',
            ),
            'notations' => array(
                'Case-study notation (in vitro): cell papers report telomere and telomerase readouts after epitalon exposure.',
                'Case-study notation: reviews describe epitalon as a pineal tetrapeptide with a still-developing evidence base.',
                'Clinical translation is limited. This page does not present outcome claims.',
            ),
            'related' => array(
                'NAD+',
                'Glutathione',
            ),
            'tokens' => array(
                'A',
                'E',
                'D',
                'G',
            ),
        ),
        'glutathione' => array(
            'kicker' => 'Immune',
            'category' => 'Immune',
            'title' => 'Glutathione',
            'subtitle' => 'Endogenous Tripeptide',
            'sequence_note' => 'γ-Glu–Cys–Gly. Glutamate is linked through its side chain, not a standard α-peptide bond.',
            'kind' => 'linear',
            'chip' => 'γ-linked tripeptide',
            'diagram' => true,
            'overview' => 'Glutathione is a tripeptide of glutamate, cysteine, and glycine found in most cells. Research literature covers its synthesis, its role in cellular redox balance, and its use as a substrate for thiol-dependent enzymes.',
            'mechanism' => 'Synthesis is controlled largely through glutamate-cysteine ligase and glutathione synthetase. The tripeptide participates in thiol-disulfide exchange and is a cofactor for glutathione peroxidases and transferases.',
            'uses' => array(
                'Cellular redox assays',
                'Glutathione synthesis pathway research',
                'Thiol-dependent enzyme studies',
                'Measurement of reduced and oxidized glutathione',
            ),
            'notations' => array(
                'Case-study notation: biosynthesis reviews describe the two-step synthesis of the tripeptide and its regulation.',
                'Case-study notation: metabolism reviews place glutathione in cellular redox systems rather than in a single pathway.',
                'This page is a research overview of the molecule. It does not present clinical outcome claims.',
            ),
            'related' => array(
                'NAD+',
                'KPV',
            ),
            'tokens' => array(),
        ),
        'igf-lr3' => array(
            'kicker' => 'Growth Factors',
            'category' => 'Growth Factors',
            'title' => 'IGF-LR3',
            'subtitle' => 'Long Arg3 IGF-I Analog',
            'sequence_note' => 'Long Arg3 IGF-I (83 aa)',
            'kind' => 'linear',
            'diagram' => true,
            'overview' => 'IGF-LR3 (Long Arg3 IGF-I) is a modified insulin-like growth factor-I analog. An arginine substitution and an N-terminal extension are studied because they reduce binding to IGF-binding proteins relative to native IGF-I.',
            'mechanism' => 'Research compares IGF-I receptor engagement and binding-protein interaction of LR3-IGF-I with native IGF-I in biochemical and animal models. It is a growth-factor analog, not a GHRH peptide.',
            'uses' => array(
                'IGF-I receptor pharmacology',
                'IGF-binding protein interaction assays',
                'Comparative growth-factor analog studies',
                'Analytical identification of LR3-IGF-I reference materials',
            ),
            'notations' => array(
                'Case-study notation: animal studies have used Long-R3-IGF-I as a probe of the somatotropic axis.',
                'Case-study notation: expression and physicochemical papers describe production and properties of LR3-IGF-I protein.',
                'Results in one model should not be generalized. This page does not present clinical outcome claims.',
            ),
            'related' => array(
                'Tesamorelin',
                'CJC-1295 (DAC)',
            ),
            'tokens' => array(
                'M',
                'F',
                'P',
                'A',
                'M',
                'P',
                'L',
                'S',
                'S',
                'L',
                'F',
                'V',
                'N',
                'G',
                'P',
                'R',
                'T',
                'L',
                'C',
                'G',
                'A',
                'E',
                'L',
                'V',
                'D',
                'A',
                'L',
                'Q',
                'F',
                'V',
                'C',
                'G',
                'D',
                'R',
                'G',
                'F',
                'Y',
                'F',
                'N',
                'K',
                'P',
                'T',
                'G',
                'Y',
                'G',
                'S',
                'S',
                'S',
                'R',
                'R',
                'A',
                'P',
                'Q',
                'T',
                'G',
                'I',
                'V',
                'D',
                'E',
                'C',
                'C',
                'F',
                'R',
                'S',
                'C',
                'D',
                'L',
                'R',
                'R',
                'L',
                'E',
                'M',
                'Y',
                'C',
                'A',
                'P',
                'L',
                'K',
                'P',
                'A',
                'K',
                'S',
                'A',
            ),
        ),
        'kisspeptin' => array(
            'kicker' => 'Hormonal',
            'category' => 'Hormonal',
            'title' => 'Kisspeptin',
            'subtitle' => 'KISS1 Neuropeptide',
            'sequence_note' => 'Kisspeptin-10 C-terminus: YNWNSFGLRF. Longer forms add a variable N-terminal extension (N+).',
            'kind' => 'linear',
            'diagram' => true,
            'overview' => 'Kisspeptin refers to peptides encoded by KISS1 that activate the KISS1R receptor, also called GPR54. Research centers on how this signaling controls GnRH neurons and the reproductive endocrine axis.',
            'mechanism' => 'Kisspeptin-KISS1R signaling is studied as an upstream input to hypothalamic GnRH release. Reviews cover receptor biology and reproductive neuroendocrinology rather than a single downstream pathway.',
            'uses' => array(
                'GnRH neuron signaling models',
                'KISS1R receptor pharmacology',
                'Reproductive-axis research',
                'Comparison of kisspeptin peptide forms',
            ),
            'notations' => array(
                'Case-study notation: reviews describe kisspeptin/GPR54 signaling as a regulator of the reproductive endocrine axis.',
                'Case-study notation: experimental papers examine kisspeptin in relation to GnRH and luteinising-hormone physiology.',
                'This catalog page does not present fertility or other clinical outcome claims.',
            ),
            'related' => array(
                'Sermorelin',
                'Tesamorelin',
            ),
            'tokens' => array(
                'Y',
                'N',
                'W',
                'N',
                'S',
                'F',
                'G',
                'L',
                'R',
                'F',
            ),
        ),
    );
}
