"""54 unique molecule looks for 14-chem-breakdown-54, in Sheet 13 row order.

Two scenes per compound. No compound name is written into a prompt.
"""

from __future__ import annotations


def L(
    look_name,
    hero,
    world,
    light,
    camera,
    color,
    hop1_move,
    hop1_action,
    hop2_move,
    hop2_action,
    keep,
):
    return {
        "look_name": look_name,
        "hero": hero,
        "world": world,
        "light": light,
        "camera": camera,
        "color": color,
        "hop1_move": hop1_move,
        "hop1_action": hop1_action,
        "hop2_move": hop2_move,
        "hop2_action": hop2_action,
        "keep": keep,
    }


LOOKS = [
    L(
        "Violet span",
        "A long kinked spiral of amino acids bridges a dark gap, each amino acid a cluster of glossy violet and ice-blue glass spheres, each new bond a white-gold flash. The newest bond sits tack sharp in the upper middle. Loose glass spheres drift in from the sides on thin streaks of light.",
        "A deep trench between two towering rope-like collagen cables, banded and lit teal along one edge, falling away into haze. Soft luminous spheres hang at different depths.",
        "White-gold bond flashes are the key light. Electric cyan rims every glass sphere. A violet glow rises from the trench. Thin volumetric beams cut the haze. Rich deep blacks.",
        "Low angle looking up the spiral, shallow depth of field, anamorphic oval bokeh from foreground spheres. The lower fifth of the frame stays dark.",
        "Electric cyan, violet, and white-gold, high contrast, filmic highlight roll-off.",
        "The camera rises slowly along the spiral and drifts right at a constant speed from the first frame to the last.",
        "New glass amino acids rise from the dark below and lock onto the spiral one after another, each bond flashing white-gold. The collagen cables shimmer along their teal edges.",
        "Keep rising and drifting right at the same speed, then pull slowly back.",
        "A white-gold wave of light runs the full length of the spiral. The pull-back reveals both collagen cables and the whole span between them.",
        "The spiral keeps its kink, its violet and ice-blue glass spheres, and its white-gold bonds for the whole shot.",
    ),
    L(
        "Peach canyon",
        "A large folded peptide of peach and champagne glass spheres rests across a ridge, its backbone a bright thread of light and its side groups round and glossy. One bend of the fold is tack sharp in the upper middle.",
        "Inside a cavern of stacked, paper-thin membrane shelves the color of warm stone, each shelf edge glowing peach, the shelves stepping down into darkness.",
        "A warm key from the peptide throws caustics on the nearest shelf. A cool shadow fills the canyon below. Soft volumetric haze. Deep blacks.",
        "Slight high angle looking down the shelves, shallow depth of field, the foreground shelf soft and dark.",
        "Peach, champagne, and deep umber, high contrast, filmic highlight roll-off.",
        "The camera glides forward and downhill along the shelves at a steady speed from the first frame to the last.",
        "The peptide's glass spheres brighten in a slow wave from the near end to the far end, and a soft ring of peach light spreads across the shelf.",
        "Continue the same downhill glide, then rise and pull back.",
        "The pull-back shows shelf after shelf receding, with the peptide still lying across the nearest ridge and a few more peach points of light far below.",
        "The peptide keeps its folded shape, peach and champagne glass, and bright backbone for the whole shot.",
    ),
    L(
        "Copper cradle",
        "One copper ion glows like a small star, molten orange-gold with a soft corona, held in a cradle of three amino acids. Every atom is clear glass that refracts the ion, so the cradle glows copper from inside. A long flexible side arm curls into the dark. Tiny copper motes drift off the ion. The cradle is tack sharp in the upper middle.",
        "A wide dark bay between curved cell-wall ribs, each rib edged in teal, with faint bioluminescent threads in the far wall and soft out-of-focus spheres at many depths.",
        "The copper ion is the key light and throws warm caustics on the nearest rib. A cool teal rim separates the cradle from the background. Thin light shafts. Deep blacks.",
        "Low angle looking slightly up, shallow depth of field, creamy anamorphic bokeh. The lower fifth stays calm and dark.",
        "Teal and copper with warm gold highlights, high contrast, filmic highlight roll-off.",
        "The camera glides slowly forward and arcs left around the cradle at a steady speed from the first frame to the last.",
        "The three amino acids draw slightly closer around the ion, every glass atom brightens in turn, the bonds flare copper-white, and a soft ring of light crosses the nearest rib. The side arm sways. Copper motes drift upward.",
        "Continue the same slow leftward arc, then gradually rise and pull back.",
        "The pull-back reveals the full bay of ribs and the far wall of faint threads. The ion pulses slowly and light keeps shimmering on the bonds. A few more copper points glint far away.",
        "The cradle keeps its exact shape, clear glass atoms, and molten copper glow for the whole shot.",
    ),
    L(
        "Amber rings",
        "Two ring-shaped molecules face each other, linked by a short bridge of amber-gold glass spheres that glow from within. The rings are clear glass with warm cores. The bridge is tack sharp at frame center. Small gold motes orbit the rings slowly.",
        "A round chamber of dark folded protein walls, the walls ribbed like a seed pod, with narrow slits of amber light between the ribs.",
        "The amber bridge is the key light. Gold rim light traces both rings. The chamber stays nearly black except for the slits. Fine haze.",
        "Straight-on, the rings centered, shallow depth of field, the near ring's edge soft in the foreground.",
        "Amber, gold, and near-black, high contrast, filmic highlight roll-off.",
        "The camera orbits the pair slowly to the right at a constant speed from the first frame to the last.",
        "The bridge brightens, a pulse of gold travels from one ring to the other, and the motes spiral a little faster. The ribbed walls shimmer in the slits of light.",
        "Continue the same rightward orbit, then pull slowly outward.",
        "The pull-back shows the whole pod chamber and the pair floating at its center, the gold pulse still traveling the bridge.",
        "The two rings and their amber bridge keep their shape, glass, and warm cores for the whole shot.",
    ),
    L(
        "Coral tail",
        "A long coral-pink peptide curves through the frame like a ribbon of glass spheres, with one slender lipid tail streaming behind it as a brighter filament. The head of the ribbon is tack sharp. The tail fades into soft bokeh.",
        "An open channel between tall translucent curtains of membrane, the curtains slowly rippling, their edges lit coral against deep navy.",
        "Coral key light on the ribbon, a cool navy fill in the channel, thin volumetric beams between the curtains, deep blacks.",
        "Side view tracking along the ribbon, shallow depth of field, foreground curtain soft.",
        "Coral, navy, and warm white highlights, high contrast, filmic highlight roll-off.",
        "The camera tracks alongside the ribbon, moving forward at a constant speed from the first frame to the last.",
        "Glass spheres along the ribbon light up in sequence from the head toward the tail, and the lipid filament waves gently. The curtains ripple.",
        "Keep tracking forward at the same speed, then drift outward from the ribbon.",
        "The drift reveals more of the curtain channel and the full length of the coral ribbon with its streaming tail.",
        "The ribbon keeps its coral glass spheres and its single bright tail for the whole shot.",
    ),
    L(
        "Cyan lantern",
        "A compact cluster of luminous cyan glass spheres hangs like a lantern, bonds between them thin rods of white light. The center sphere is tack sharp and brightest. Smaller cyan motes orbit it.",
        "A night field of soft black folds, like heavy velvet membranes, with a few distant cyan specks and one pale arc of a cell wall far behind.",
        "The lantern is the only real key light, spilling cyan onto the nearest fold. A faint cool rim from the far wall. Deep blacks everywhere else.",
        "Close, slightly below, shallow depth of field, the orbiting motes as oval bokeh.",
        "Cyan against near-black, with white bond highlights, high contrast, filmic highlight roll-off.",
        "The camera pushes in very slowly toward the lantern at a constant speed from the first frame to the last.",
        "The center sphere pulses brighter, the white bonds flare in a ring, and the orbiting motes swing wider. The nearest black fold catches more cyan light.",
        "Continue the slow push, then ease into a gentle rise.",
        "The rise shows the lantern against a larger stretch of the dark folds and the pale far wall.",
        "The cluster keeps its cyan glass spheres and white bonds for the whole shot.",
    ),
    L(
        "Platinum helix",
        "A pale platinum helix of glass spheres turns through the frame, each turn evenly spaced, the bonds slim and silver-white. One turn at the upper middle is tack sharp. A faint mist of tiny platinum motes follows the helix.",
        "A tall vertical shaft inside a living cell, the walls smooth and dark with thin horizontal rings of cool light, like galleries receding upward.",
        "Cool overhead light slides down the helix. Silver highlights on the near spheres. The shaft below falls into black. Fine haze.",
        "Low angle looking up the shaft, shallow depth of field, the nearest turn large and sharp.",
        "Platinum, silver, and cold blue-gray, high contrast, filmic highlight roll-off.",
        "The camera rises with the helix at a steady speed from the first frame to the last.",
        "Each turn of the helix brightens as the camera passes it, silver light running upward turn by turn. The gallery rings drift past.",
        "Keep rising at the same speed, then the climb slows into a wide upward view without stopping.",
        "More of the shaft opens above, gallery after gallery, the helix still turning up into the haze.",
        "The helix keeps its even turns, platinum glass, and silver bonds for the whole shot.",
    ),
    L(
        "Wine ring",
        "A closed ring of wine-rose glass spheres floats face-on, the ring slightly tilted, silver bonds between the spheres. One sphere on the near edge is tack sharp. A few loose rose spheres drift just outside the ring.",
        "A dark circular atrium with a domed ceiling of dim membrane, a ring of tiny warm lights around the dome's base.",
        "Soft warm practicals from the dome lights, a cooler fill on the ring's far side, the center of the atrium black. Gentle haze.",
        "Three-quarter view, the ring large in frame, shallow depth of field, foreground sphere crisp.",
        "Wine-rose, silver, and warm amber points, high contrast, filmic highlight roll-off.",
        "The camera circles the ring slowly to the left at a constant speed from the first frame to the last.",
        "Silver bonds flare one after another around the ring, and the loose spheres drift closer, two of them settling into gaps. The dome lights twinkle.",
        "Continue the leftward circle, then rise above the ring.",
        "From above, the whole atrium and the dome's ring of lights come into view, the wine-rose ring still turning slowly under the camera.",
        "The ring keeps its closed shape, wine-rose glass, and silver bonds for the whole shot.",
    ),
    L(
        "Terracotta braid",
        "Two glass strands, one terracotta and one gold, twist around each other into a single braid. Where they touch, the bonds flash warm white. The tightest crossing is tack sharp at frame center.",
        "A dry-looking canyon of layered membrane, the layers the color of fired clay, a gold thread of light running along the canyon floor into the distance.",
        "Warm side light rakes the braid. Gold bounce from the floor thread. The canyon walls fall into brown shadow. Light haze.",
        "Level with the braid, looking down the canyon, shallow depth of field.",
        "Terracotta, gold, and deep brown, high contrast, filmic highlight roll-off.",
        "The camera dollies forward along the braid at a constant speed from the first frame to the last.",
        "The white flashes travel along the crossings toward the distance, and the two strands seem to draw a fraction tighter without changing their twist. Dust-fine motes drift in the light.",
        "Keep dollying forward, then drift up and to the right.",
        "The rise shows the braid lying in the canyon and the gold floor-thread running far ahead.",
        "The braid keeps both strands, their twist, and their terracotta and gold glass for the whole shot.",
    ),
    L(
        "Sunlit mote",
        "A small compact peptide of sunlit gold glass spheres sits like a seed, only a handful of atoms, with a brighter core sphere. It is tack sharp. A thin halo of finer gold dust surrounds it.",
        "The interior of a rounded organelle, the inner wall folded into shelves that catch gold light, the space otherwise dark and immense compared with the tiny peptide.",
        "The core sphere is the key. Gold light pools on the nearest shelf. The rest of the organelle is deep shadow. Fine haze.",
        "Macro close-up, the peptide small in a large frame, shallow depth of field, shelves soft behind.",
        "Sunlit gold against deep olive shadow, high contrast, filmic highlight roll-off.",
        "The camera pushes past the peptide very slowly, arcing right, at a constant speed from the first frame to the last.",
        "The core pulses once, the halo of dust expands a little, and a faint gold ripple crosses the nearest shelf.",
        "Continue the slow rightward arc and begin to pull back.",
        "The pull-back reveals how small the peptide is inside the huge folded organelle, more shelves appearing in the gold haze.",
        "The peptide keeps its compact gold glass shape and brighter core for the whole shot.",
    ),
    L(
        "Mint filament",
        "A short straight chain of cool mint glass spheres, only a few links long, hangs horizontally. Silver-green bonds. The middle link is tack sharp. The ends soften slightly.",
        "A quiet pool of dark cytosol under a low ceiling of pale membrane, the ceiling faintly green, a few bubbles of light suspended motionless.",
        "Soft top light from the ceiling, mint highlights on the upper spheres, the pool below almost black. Calm haze.",
        "Eye level on the chain, centered, shallow depth of field, one foreground bubble as oval bokeh.",
        "Mint, silver-green, and deep teal-black, high contrast, filmic highlight roll-off.",
        "The camera slides laterally to the right along the chain at a constant speed from the first frame to the last.",
        "Each sphere brightens as the camera passes, a green-white flash hopping from link to link. The ceiling's pale light shivers.",
        "Keep sliding right, then nose down slightly and continue.",
        "The downward drift shows the dark pool under the chain and more suspended bubbles receding into green haze.",
        "The short chain keeps its straight shape and mint glass spheres for the whole shot.",
    ),
    L(
        "Teal lattice",
        "An open lattice of ocean-teal glass spheres, ball-and-stick, with a denser knot of spheres at the center. The knot is tack sharp. Outer sticks fade into bokeh.",
        "A forest of slender protein pillars underwater-dark, teal light leaking between them, the floor lost in fog.",
        "Teal shafts between the pillars. The lattice's center is the brightest object. Deep navy shadows. Visible haze.",
        "Looking through the pillars toward the lattice, shallow depth of field, a near pillar soft at frame left.",
        "Ocean teal, navy, and pale aqua highlights, high contrast, filmic highlight roll-off.",
        "The camera weaves slowly forward between the pillars toward the lattice at a constant speed from the first frame to the last.",
        "The center knot brightens and a teal pulse runs out along the sticks. Pillars drift past the lens.",
        "Continue forward, then bank gently left and keep moving.",
        "The bank reveals a wider stand of pillars and the lattice hanging among them, the pulse still fading outward.",
        "The lattice keeps its teal glass spheres and its dense center knot for the whole shot.",
    ),
    L(
        "Amber speck",
        "A tiny compact molecule, warm amber carbon spheres and cool gray glass spheres packed tight, no long chain. It floats alone and tack sharp, smaller than the worlds around it. A few amber motes peel off and drift.",
        "A vast dim plaza of a cell interior, distant organelles as soft monuments, the floor a dark reflective membrane.",
        "The molecule is a small warm key in a huge cool space. A faint gray rim from an unseen source. The plaza falls off to black. Light haze.",
        "Wide frame with the molecule still readable at center, shallow depth of field, monuments as bokeh.",
        "Amber and cool gray against a blue-black field, high contrast, filmic highlight roll-off.",
        "The camera creeps forward toward the speck at a constant speed from the first frame to the last.",
        "The amber spheres brighten in a quick ring, gray spheres answer a beat later, and the peeled motes drift upward.",
        "Keep creeping forward, then rise over the speck.",
        "The rise shows the reflective floor and how far the monuments sit from the tiny molecule.",
        "The molecule keeps its tight amber-and-gray packing for the whole shot.",
    ),
    L(
        "Champagne coil",
        "A long neat helix of champagne-gold glass spheres, specular highlights running along the near edge. One central turn is tack sharp. The helix leans slightly as it rises.",
        "A bright-edged cleft in a dark organelle wall, the cleft lined with soft gold filament, opening onto black space beyond.",
        "Gold rim light from the cleft, the helix catching speculars, the space beyond pure black. Fine haze in the cleft only.",
        "Three-quarter low angle, the helix climbing out of the cleft, shallow depth of field.",
        "Champagne gold and black, with soft white speculars, high contrast, filmic highlight roll-off.",
        "The camera climbs with the helix, drifting left, at a constant speed from the first frame to the last.",
        "Specular highlights travel up the near edge turn by turn. Gold filament in the cleft stirs.",
        "Keep climbing and drifting left, then ease back from the wall.",
        "The ease-back shows the cleft, the leaning helix, and the black opening beyond.",
        "The helix keeps its champagne glass turns and its lean for the whole shot.",
    ),
    L(
        "Opal trio",
        "Three white-opal glass spheres joined in a short chain, rose-gold bonds between them, the middle sphere tack sharp and slightly larger. A soft inner glow, no hard core.",
        "A pale fog bank inside a cell, visibility short, a few darker membrane ribbons sliding through the fog at different depths.",
        "The opal spheres glow from inside. Rose-gold bonds are the warm accents. The fog eats the light within a short distance. Soft, not flat.",
        "Close and frontal, the trio filling the middle, shallow depth of field, a ribbon crossing soft in front.",
        "White-opal, rose-gold, and gray fog, gentle contrast, filmic highlight roll-off.",
        "The camera drifts right and slightly closer at a constant speed from the first frame to the last.",
        "The rose-gold bonds flare softly in order, left then right, and the middle sphere's inner glow swells and eases. Fog ribbons slide past.",
        "Continue the rightward drift, then float upward.",
        "The rise lifts the trio out of the thickest fog, more dark ribbons visible below.",
        "The three opal spheres and their rose-gold bonds keep their short-chain shape for the whole shot.",
    ),
    L(
        "Gold stair",
        "A tidy helix of champagne-gold glass spheres climbs like a stair, each step one turn. The nearest step is tack sharp. Highlights are clean and metallic-soft, not harsh.",
        "A spiral ramp of dark membrane winding upward around a central void, the ramp's outer lip edged in dim gold.",
        "Gold lip-light on the ramp, the helix brighter than the ramp, the central void black. Slight haze.",
        "Looking up the spiral, the helix and ramp echoing each other, shallow depth of field.",
        "Champagne gold and charcoal, high contrast, filmic highlight roll-off.",
        "The camera follows the ramp upward, rotating slowly with it, at a constant speed from the first frame to the last.",
        "Each helix step lights as the camera comes level with it, a gold glint hopping upward. The ramp's lip shimmers.",
        "Keep rotating upward, then widen the orbit.",
        "The wider orbit shows more of the void and several turns of both ramp and helix.",
        "The helix keeps its even champagne-gold steps for the whole shot.",
    ),
    L(
        "Bronze loop",
        "A closed cyclic peptide of bronze and deep-rose glass spheres, the loop upright like a pendant. Bronze spheres on one half, rose on the other. The bottom of the loop is tack sharp.",
        "A narrow vertical niche in a dark cell wall, the niche walls rough with protein texture, a single shaft of warm light from above.",
        "Top light in the niche, bronze catching it first, rose falling into warmer shadow. The niche mouth is black. Light haze in the shaft.",
        "Straight into the niche, the loop centered, shallow depth of field.",
        "Bronze, deep rose, and warm black, high contrast, filmic highlight roll-off.",
        "The camera rises inside the niche at a constant speed from the first frame to the last.",
        "A warm glint travels from the bronze half around to the rose half. The loop turns a few degrees, still a closed ring.",
        "Keep rising, then tilt up toward the shaft without stopping.",
        "The tilt reveals the light shaft's source as a bright slit far above and the loop still hanging in the niche.",
        "The loop keeps its closed shape and its bronze and deep-rose glass for the whole shot.",
    ),
    L(
        "Teal-gold dart",
        "A short dart-shaped peptide, teal glass spheres along the body and a gold glass tip. The tip is tack sharp. A faint trail of teal motes behind it.",
        "Open dark space just inside a cell membrane, the membrane a vast curved wall on the right, dim and smooth, the left side falling to black.",
        "The gold tip is the key, throwing a small warm pool. Teal body light is cooler. The membrane gets a thin rim. Deep blacks.",
        "Behind and slightly below the dart, looking along it toward the membrane, shallow depth of field.",
        "Teal, gold, and ink black, high contrast, filmic highlight roll-off.",
        "The camera follows the dart as it drifts toward the membrane at a constant slow speed from the first frame to the last.",
        "The gold tip pulses, teal motes stream back past the camera, and a soft reflection appears on the membrane.",
        "Keep following, then slide sideways along the membrane.",
        "The slide shows a long stretch of the curved wall and the dart still approaching, small against it.",
        "The dart keeps its teal body, gold tip, and short shape for the whole shot.",
    ),
    L(
        "Pale ribbon",
        "A short pale-gold ribbon of glass spheres with silver side-chain beads spaced along it. The ribbon is gently curved. The middle bead is tack sharp and brightest.",
        "A shallow basin of dark fluid-like cytosol, the surface a mirror, low fog, a distant glow on the horizon of the basin.",
        "Low warm horizon light, silver beads sparking, the ribbon's underside reflected in the basin. Soft contrast in the fog, deep at the edges.",
        "Just above the surface, the ribbon and its reflection both visible, shallow depth of field.",
        "Pale gold, silver, and dark olive, filmic highlight roll-off.",
        "The camera skims forward just above the basin at a constant speed from the first frame to the last.",
        "Silver beads flash in order along the ribbon, and the reflection flashes with them. Fog slides past the lens.",
        "Keep skimming, then climb a little and continue forward.",
        "The climb shows more of the basin and the distant horizon glow, the ribbon still skimming its own reflection.",
        "The ribbon keeps its pale-gold glass and silver beads for the whole shot.",
    ),
    L(
        "Pink-teal fuse",
        "Two peptide ribbons, one translucent pink and one teal, fused into one linked complex, not two separate objects. They share a bright white junction that is tack sharp. Glass spheres on both ribbons.",
        "A crossroads of four membrane corridors meeting in a dark hub, pink light down one corridor, teal down the opposite, the other two nearly black.",
        "The junction is the key, white and hot. Pink and teal fill their corridors. The hub corners are black. Haze in the lit corridors only.",
        "Looking down the pink corridor toward the junction, shallow depth of field, the teal corridor visible beyond.",
        "Pink, teal, and white at the join, high contrast, filmic highlight roll-off.",
        "The camera pushes down the pink corridor toward the junction at a constant speed from the first frame to the last.",
        "Glass spheres on the pink ribbon light toward the junction, then the teal ribbon answers, the white junction flaring once.",
        "Arrive near the junction and arc slowly into the teal corridor without a cut.",
        "The arc looks back at the fused pair from the teal side, both corridors still lit, the complex unchanged.",
        "The two ribbons stay fused as one complex, pink and teal glass, white junction, for the whole shot.",
    ),
    L(
        "Sky chain",
        "A short chain of electric-sky-blue glass spheres, bright and clean, bonds of pale white. The leading sphere is tack sharp and slightly ahead of the others, as if the chain is in motion.",
        "A high open vault, the ceiling a huge pale membrane dome far above, shafts of blue-white light dropping through rifts.",
        "The shafts are cool and hard. The chain glows sky blue from inside. Shadows on the floor are long. Clear air, slight haze only in the shafts.",
        "Low and wide, the chain in the lower third, the dome filling the top, shallow depth of field on the leading sphere.",
        "Electric sky blue, white, and pale gray, high contrast, filmic highlight roll-off.",
        "The camera booms up slowly while the chain drifts forward, constant speed from the first frame to the last.",
        "The leading sphere flares, the white bonds ripple backward along the chain, and dust in a light shaft turns slowly.",
        "Keep booming up and let the chain continue forward under the camera.",
        "The higher view shows the dome's rifts and the small blue chain crossing the vault floor of light.",
        "The chain keeps its sky-blue glass spheres and pale bonds for the whole shot.",
    ),
    L(
        "Copper blend",
        "A warm cluster of copper-gold glass spheres with one brighter copper sphere at the heart. The heart is tack sharp. Outer spheres are looser, almost a cloud, still one object.",
        "A low cave of overlapping membrane lobes, copper light soaking the near lobe, the deep cave green-black.",
        "The copper heart is the key and throws warm caustics on the lobe. Gold rim on outer spheres. The cave throat is black. Haze.",
        "Inside the cluster, looking out past a soft gold sphere toward the copper heart, shallow depth of field.",
        "Copper, gold, and green-black, high contrast, filmic highlight roll-off.",
        "The camera slips between the outer spheres toward the heart at a constant speed from the first frame to the last.",
        "The heart pulses, outer spheres brighten inward, and caustics crawl across the near lobe.",
        "Pass the heart and continue out the far side without stopping.",
        "Beyond the cluster the cave opens, the copper-gold cloud now behind the camera's shoulder and still glowing.",
        "The cluster keeps its copper heart and gold glass cloud for the whole shot.",
    ),
    L(
        "Coral helix",
        "A long helix in soft coral glass with a brighter metallic-looking backbone thread. Turns are wide and regular. One turn at eye level is tack sharp. Coral motes float off the outer edge.",
        "A colonnade of thick pale protein columns in a dark hall, the floor reflective, the far end lost.",
        "Soft coral fill from the helix, cool gray light on the columns, reflections in the floor. Deep background. Light haze.",
        "Eye level between two columns, the helix beyond them, shallow depth of field, near column soft.",
        "Soft coral, metallic silver backbone, cool gray columns, filmic highlight roll-off.",
        "The camera walks the colonnade forward at a constant speed from the first frame to the last.",
        "The backbone thread lights from the near turn toward the far turns, and coral motes drift between the columns.",
        "Keep walking, then pan slowly toward the helix while still moving forward.",
        "The pan brings a long stretch of helix into view down the hall, columns sliding past.",
        "The helix keeps its wide coral turns and bright backbone for the whole shot.",
    ),
    L(
        "Ivory bronze",
        "A ribbon of ivory glass spheres with bronze beads set along one edge, the ribbon folding once like a sash. The fold is tack sharp. Ivory is luminous, bronze is darker and warmer.",
        "A quiet side-chapel of a cell, curved membrane walls, a single bronze-colored slit of light high on the left wall.",
        "Slit light rakes the ribbon. Ivory spheres glow softly on their own. The chapel is dim, not black. Fine haze in the slit.",
        "Three-quarter view of the folded sash, shallow depth of field, wall texture soft behind.",
        "Ivory, bronze, and warm gray, filmic highlight roll-off.",
        "The camera arcs left around the fold at a constant speed from the first frame to the last.",
        "Bronze beads catch the slit light one by one, and the ivory fold brightens along its crease.",
        "Continue the left arc, then rise toward the slit.",
        "The rise shows the slit, the curved walls, and the sash still folded below.",
        "The ribbon keeps its single fold, ivory glass, and bronze beads for the whole shot.",
    ),
    L(
        "Lavender seed",
        "A compact dusk-lavender peptide, a small cluster of matte-gloss glass spheres, darker at the core and paler at the rim. The core is tack sharp. No long chain.",
        "A blue-hour interior, membranes the color of late sky, a low fog, distant lavender pinlights like far windows.",
        "Dim ambient blue, the cluster's own pale rim light, no hard key. The fog softens distance. Still enough contrast to read the spheres.",
        "Close, slightly above, shallow depth of field, pinlights as soft bokeh.",
        "Dusk lavender, blue-gray, and pale lilac highlights, filmic highlight roll-off.",
        "The camera descends slowly toward the cluster at a constant speed from the first frame to the last.",
        "The pale rim brightens in a slow breath, the darker core stays steady, and fog eddies past.",
        "Keep descending, then level out and creep forward.",
        "Forward, the cluster sits in a wider field of fog and distant pinlights, still the same small shape.",
        "The cluster keeps its compact lavender glass and darker core for the whole shot.",
    ),
    L(
        "Stacked pair",
        "Two helices stacked as one complex, the lower helix champagne glass and the upper helix ice-blue glass, touching at a bright shared collar. The collar is tack sharp. They are one object, not two heroes.",
        "A vertical well with a ring-shaped balcony of membrane halfway up, the well dark above and below, the balcony lip lit faintly gold and blue.",
        "The collar is the key, half warm and half cool. Balcony lip catches both colors. The well is black. Slight haze at the balcony only.",
        "Level with the collar, the two helices extending out of focus up and down, shallow depth of field.",
        "Champagne, ice blue, and black, high contrast, filmic highlight roll-off.",
        "The camera orbits the collar slowly to the right at a constant speed from the first frame to the last.",
        "Light runs from the collar up the ice-blue helix and down the champagne helix at the same time. The balcony lip shimmers.",
        "Continue the orbit, then crane up along the ice-blue helix.",
        "The crane shows the upper helix against the dark well and the balcony falling away below, the pair still joined.",
        "The two helices stay stacked as one complex, champagne and ice-blue, for the whole shot.",
    ),
    L(
        "Gold and ice",
        "Two helices locked as one stacked complex, gold glass below and ice-blue glass above, a thin bright seam where they meet. The seam is tack sharp. Side groups are small glossy spheres.",
        "A frozen-looking shelf of membrane jutting into a dark volume, frost-like protein texture, pale blue mist under the shelf and warm dark above.",
        "Cool mist-light from below, a warmer glint on the gold helix, the seam brightest. High contrast, visible mist.",
        "From under the shelf looking up at the complex, shallow depth of field, shelf edge soft in the foreground.",
        "Gold, ice blue, and pale mist, high contrast, filmic highlight roll-off.",
        "The camera rises from under the shelf, passing the seam, at a constant speed from the first frame to the last.",
        "The seam flares, gold spheres below light in a wave, ice-blue spheres above answer. Mist curls.",
        "Clear the shelf and keep rising into the dark above.",
        "Above the shelf the complex is silhouetted against nothing, still gold below and ice blue above, mist trailing off the lip.",
        "The stacked complex keeps its seam and both colors for the whole shot.",
    ),
    L(
        "Gold river",
        "A long helix of champagne glass spheres lies almost horizontal, like a river of light, speculars racing along the top edge. A single turn near the camera is tack sharp.",
        "A broad dark floodplain of membrane, low and wet-looking, with slow gold channels of light braided across it.",
        "Low gold light from the channels, the helix brighter than the ground, the sky of the cell a deep warm black. Light haze.",
        "Helicopter-low, skimming the floodplain toward the helix, shallow depth of field.",
        "Champagne gold on near-black, filmic highlight roll-off.",
        "The camera skims forward along the helix at a constant speed from the first frame to the last.",
        "Speculars run ahead of the camera along the top edge, and a gold channel below brightens in step.",
        "Keep skimming, then gain a little height and continue.",
        "The higher skim shows the braid of gold channels and the helix running straight to the haze.",
        "The helix keeps its long champagne glass form for the whole shot.",
    ),
    L(
        "Rose link",
        "Three opal glass spheres in a shallow arc, rose-gold rods between them, the right-hand sphere tack sharp and leaning as if the arc is about to close.",
        "A dark bowl of a membrane crater, the rim catching rose light, the bowl's center a soft black.",
        "Rose rim light, the opal spheres glowing from inside, the bowl absorbing light. Fine haze above the rim.",
        "Across the crater, the arc on the near rim, shallow depth of field.",
        "Opal white, rose gold, and black, filmic highlight roll-off.",
        "The camera circles the crater rim to the left at a constant speed from the first frame to the last.",
        "The rose-gold rods flare from left to right, and the leaning sphere eases a fraction closer to its neighbor without touching.",
        "Continue around the rim, then look down into the bowl while still moving.",
        "The downward look shows the black center and the three spheres still bright on the rim.",
        "The three opal spheres keep their arc and rose-gold rods for the whole shot.",
    ),
    L(
        "Helix gate",
        "A champagne-gold helix stands in a narrow gate of membrane, the gate jaws just wider than the helix. The turn framed by the gate is tack sharp.",
        "A wall of dark stacked membrane with one vertical opening, gold light leaking through the opening into a black foreground.",
        "Backlight from the gate, the helix rim-lit gold, the foreground almost pure black. Slight haze in the opening.",
        "From the dark side, looking through the gate at the helix, shallow depth of field.",
        "Gold and black, high contrast, filmic highlight roll-off.",
        "The camera pushes through the gate toward the helix at a constant speed from the first frame to the last.",
        "Gold light swells in the opening, and each turn of the helix catches it in order from top to bottom.",
        "Pass the helix and keep moving into the light beyond the gate.",
        "Beyond the gate a larger gold-lit chamber appears, the helix now behind, still standing in the opening.",
        "The helix keeps its champagne turns for the whole shot.",
    ),
    L(
        "Rose window",
        "A cyclic loop of deep-rose and bronze glass spheres seen flat, like a round window, the near bronze sphere tack sharp, the far side softer.",
        "A round oculus in a thick dark wall, the loop filling the oculus, a dim hall visible through the center.",
        "Dim hall light behind the loop, bronze catching a warmer edge, rose falling softer. The wall is near black.",
        "Head-on to the oculus, the loop large, shallow depth of field on the near sphere.",
        "Deep rose, bronze, and black, filmic highlight roll-off.",
        "The camera dollies in toward the oculus at a constant speed from the first frame to the last.",
        "A glint travels clockwise around the loop, bronze then rose. The hall beyond shifts slightly as the camera advances.",
        "Keep dollying, then drift up so the oculus slides lower in frame.",
        "The drift shows the thick wall around the oculus and the loop still filling the round opening.",
        "The loop keeps its closed rose-and-bronze shape for the whole shot.",
    ),
    L(
        "Gold tip trail",
        "A short dart of teal glass with a gold glass tip, hanging vertical with the tip down, the tip tack sharp.",
        "A tall dark cistern, walls beaded with tiny water-like droplets of light, a gold reflection waiting on the floor far below.",
        "The gold tip lights the droplets nearest it. Teal fill on the body. The cistern below is black until the floor reflection. Haze.",
        "Above the dart looking down past it, shallow depth of field, tip sharp, floor soft.",
        "Teal, gold, and black, high contrast, filmic highlight roll-off.",
        "The camera descends beside the dart at a constant speed from the first frame to the last.",
        "The tip pulses and a thin gold reflection on the floor grows brighter. Droplets of light slide down the walls.",
        "Keep descending past the tip toward the floor.",
        "The floor reflection becomes a gold disc, the dart still hanging above it, unchanged.",
        "The dart keeps its teal body and gold tip for the whole shot.",
    ),
    L(
        "Silver beads",
        "A pale-gold ribbon stands nearly vertical, silver side-chain beads sticking out like dew. The uppermost bead is tack sharp.",
        "A narrow crevice of dark tissue, both walls close, a thin silver thread of light falling from a crack overhead.",
        "Overhead silver thread, beads sparking, the ribbon's gold softer. Crevice depths are black. Fine haze in the thread.",
        "Looking up the crevice, the ribbon centered, shallow depth of field.",
        "Pale gold, silver, and black, filmic highlight roll-off.",
        "The camera climbs the crevice at a constant speed from the first frame to the last.",
        "Silver beads flash from the bottom of the ribbon upward, chasing the camera. The overhead thread brightens.",
        "Keep climbing toward the crack.",
        "The crack widens in frame, silver light pouring past the ribbon, the ribbon still vertical.",
        "The ribbon keeps its pale-gold glass and silver beads for the whole shot.",
    ),
    L(
        "Shared knot",
        "Pink and teal glass ribbons tied in one knot, a single complex, the knot's center a white-hot glass junction that is tack sharp. Loose ends trail up and down.",
        "A dark knot of membrane fibers echoing the hero, fibers thick as cables, some pink-lit, some teal-lit, most black.",
        "The white junction is the key. Pink and teal cable edges catch color. Gaps between cables are black. Haze.",
        "Inside the cable knot, the glass junction centered, shallow depth of field, a near cable soft.",
        "Pink, teal, and white, high contrast, filmic highlight roll-off.",
        "The camera rotates around the junction at a constant speed from the first frame to the last.",
        "The white junction flares, then pink spheres light along one tail and teal spheres along the other.",
        "Keep rotating, then pull out through a gap in the cables.",
        "Outside the cable knot, the fused glass complex is a small bright knot in a larger dark tangle.",
        "The pink and teal ribbons stay one knotted complex for the whole shot.",
    ),
    L(
        "Blue rung",
        "A short sky-blue glass chain hung like a rung between two dark anchors of protein, the middle sphere tack sharp, the anchors soft.",
        "A gap in a scaffold of black protein beams, blue-white light far below the gap, the beams receding in perspective.",
        "Uplight from the blue-white below, the chain glowing sky blue, beams in silhouette. High contrast. Slight haze below.",
        "Across the gap, the chain horizontal and centered, shallow depth of field.",
        "Sky blue, white, and black beams, filmic highlight roll-off.",
        "The camera tracks left along the chain at a constant speed from the first frame to the last.",
        "White bonds ripple from the right anchor to the left, and the blue uplight shivers on the spheres.",
        "Keep tracking left, then drop slightly into the gap.",
        "The drop shows the depth of the scaffold and the blue-white light far under the chain.",
        "The chain keeps its short sky-blue glass shape between the anchors for the whole shot.",
    ),
    L(
        "Heart cave",
        "A loose cloud of copper-gold glass with a single hotter copper sphere buried off-center, that sphere tack sharp, the cloud asymmetrical.",
        "A side pocket of a larger cave, the mouth a copper-lit oval, the pocket itself green-black and close.",
        "Copper light from the mouth and from the hot sphere. Gold rims on the near glass. The pocket corners are black.",
        "From the pocket mouth looking in, the hot sphere deep in the cloud, shallow depth of field.",
        "Copper, gold, and green-black, high contrast, filmic highlight roll-off.",
        "The camera enters the pocket slowly at a constant speed from the first frame to the last.",
        "The hot sphere pulses and the asymmetrical cloud brightens from that side outward. The oval mouth shrinks behind.",
        "Move past the cloud toward the back wall, still slow.",
        "The back wall comes close, copper light, the cloud now between camera and mouth.",
        "The cloud keeps its off-center copper sphere and gold glass for the whole shot.",
    ),
    L(
        "Backbone arc",
        "A coral helix bent into a wide arc, metallic backbone on the inside of the arc, coral glass on the outside. The apex of the arc is tack sharp.",
        "A dark amphitheater of membrane tiers, empty, the tiers catching a thin coral wash.",
        "The backbone throws a hard silver-coral key. Tiers fall off quickly to black. Light haze over the apex.",
        "From the stands, looking at the arc, shallow depth of field, a near tier soft at the bottom.",
        "Coral, silver, and black tiers, filmic highlight roll-off.",
        "The camera cranes from the stands toward the apex at a constant speed from the first frame to the last.",
        "The backbone lights from one foot of the arc to the other, passing the apex. Coral motes lift off the outer edge.",
        "Reach the apex and travel along the arc toward the far foot.",
        "The far foot of the arc and more dark tiers come into view, the helix unchanged.",
        "The arc keeps its coral glass and metallic inner backbone for the whole shot.",
    ),
    L(
        "Sash shadow",
        "An ivory glass ribbon with bronze beads, folded twice this time, like a sash dropped in midair. The upper fold is tack sharp.",
        "A tall dim cloister, repeating membrane arches, a bronze slit at the far end only.",
        "Far slit light, long and soft, ivory spheres self-luminous, bronze beads darker. The cloister recedes to gray-black.",
        "Down the cloister toward the sash, shallow depth of field, nearest arch soft.",
        "Ivory, bronze, and gray-black, filmic highlight roll-off.",
        "The camera walks the cloister toward the sash at a constant speed from the first frame to the last.",
        "The upper fold brightens, bronze beads tick on one after another, arches slide past.",
        "Pass the sash and continue toward the slit.",
        "The slit grows, the twice-folded sash now behind, still hanging in the cloister.",
        "The ribbon keeps both folds, ivory glass, and bronze beads for the whole shot.",
    ),
    L(
        "Lilac drift",
        "A small dusk-lavender cluster drifting, paler glass on the outside, a dusk core tack sharp, a short faint tail of lilac motes.",
        "An open night volume with slow horizontal bands of blue membrane far apart, like distant strata.",
        "No hard key. The cluster's pale rim is the light. Strata are dim blue. Plenty of black between them.",
        "Alongside the cluster, matching its drift, shallow depth of field, strata soft.",
        "Dusk lavender and dim blue, filmic highlight roll-off.",
        "The camera matches the cluster's drift, easing right, at a constant speed from the first frame to the last.",
        "The lilac tail lengthens a little, the core stays steady, and a stratum slides slowly through the background.",
        "Keep the drift, then rise relative to the cluster.",
        "The rise puts a stratum between camera and cluster for a moment, then clears, the cluster unchanged.",
        "The cluster keeps its compact lavender glass and dusk core for the whole shot.",
    ),
    L(
        "Collar well",
        "Champagne helix below, ice-blue helix above, one shared collar, the collar tack sharp and brighter than either helix. One complex.",
        "A round well seen from the rim, black water-like cytosol far down, a thin ring of mixed gold and blue light at the rim.",
        "The collar lights the rim. Gold falls downward, ice blue rises. The well center is black. Haze at the rim.",
        "On the rim looking across the well, the complex rising through frame center, shallow depth of field.",
        "Champagne, ice blue, and black, high contrast, filmic highlight roll-off.",
        "The camera circles the rim at a constant speed from the first frame to the last.",
        "The collar flares and light splits, gold down the lower helix, ice blue up the upper helix.",
        "Keep circling, then lean out over the well.",
        "The lean shows the black depth and the full stacked complex still joined at the collar.",
        "The helices stay one stacked complex for the whole shot.",
    ),
    L(
        "Seam shelf",
        "Gold helix and ice-blue helix joined on a horizontal seam, the seam a bright glass bar tack sharp, both helices short and stout. One complex.",
        "A flat shelf of pale membrane in a dark volume, the shelf edge sharp, mist only below the edge.",
        "Seam light splits warm and cool across the shelf. Below the edge is blue-black mist. Above is empty black.",
        "Table-height on the shelf, the seam centered, shallow depth of field, shelf edge soft in front.",
        "Gold, ice blue, and pale shelf, filmic highlight roll-off.",
        "The camera tracks along the seam from gold toward ice blue at a constant speed from the first frame to the last.",
        "The bright bar pulses, gold spheres light behind the camera, ice-blue spheres light ahead.",
        "Run off the end of the seam and continue over the edge.",
        "Over the edge the mist is below and the joined helices remain on the shelf behind, still one object.",
        "The complex keeps its horizontal seam and both colors for the whole shot.",
    ),
    L(
        "Glass tide",
        "A violet and ice-blue glass spiral lies on its side like a tide line, white-gold bonds along the crest. The nearest crest bond is tack sharp. Loose spheres wash in from frame left.",
        "A dark sloping membrane beach, the slope running down to the right, a cyan edge-light on the horizon of the slope.",
        "Cyan horizon rim, white-gold crest flashes, violet fill in the hollows of the spiral. Deep blacks downslope. Haze at the horizon.",
        "Low on the slope, looking along the spiral, shallow depth of field.",
        "Violet, ice blue, white-gold, and cyan, high contrast, filmic highlight roll-off.",
        "The camera crabs right, downhill, at a constant speed from the first frame to the last.",
        "Loose spheres join the crest, each new bond flashing white-gold, the spiral growing by a link or two without changing its colors.",
        "Keep crabbing downhill, then lift.",
        "The lift shows the slope, the cyan horizon, and the whole side-lying spiral.",
        "The spiral keeps its violet and ice-blue glass and white-gold bonds for the whole shot.",
    ),
    L(
        "Shelf giant",
        "A huge peach-and-champagne peptide draped over the lip of a single giant shelf, glass spheres large in frame, one champagne sphere tack sharp.",
        "One enormous membrane shelf in an otherwise empty dark, the shelf thick, its underside lost, its top softly peach.",
        "Peach light from the peptide across the shelf top. The void around the shelf is black. A little haze on the lip.",
        "At the lip, the peptide huge, shallow depth of field, the void behind.",
        "Peach, champagne, and black, filmic highlight roll-off.",
        "The camera slides along the lip under the peptide at a constant speed from the first frame to the last.",
        "Champagne spheres brighten in a slow sequence, and a peach wash spreads farther across the shelf.",
        "Slide out from under the peptide into open dark, still moving.",
        "Open dark, then the shelf lip and the draped peptide shrink as the camera keeps going.",
        "The peptide keeps its peach and champagne glass and its draped shape for the whole shot.",
    ),
    L(
        "Ion motes",
        "A copper ion like a small star inside a three-part glass cradle, a long side arm, copper motes already scattered wider than in a tight close-up. The ion is tack sharp. The cradle is a little smaller in a wider frame.",
        "A field of many thin teal fibers crossing at random, like a loose net, dark space between the fibers, a few fibers close to the lens.",
        "The ion throws warm caustics on nearby fibers. Teal rim on the glass. Most of the net is black. Haze.",
        "Through the net, a near fiber soft across the corner, the cradle sharp beyond, shallow depth of field.",
        "Copper and teal, high contrast, filmic highlight roll-off.",
        "The camera pushes through the net toward the cradle at a constant speed from the first frame to the last.",
        "Fibers slide past. The ion pulses, motes drift outward, and the side arm sways once.",
        "Clear the last fibers and arc slowly left around the cradle.",
        "The arc shows more of the net and the cradle still holding the molten copper ion.",
        "The cradle keeps its three glass parts, side arm, and copper ion for the whole shot.",
    ),
    L(
        "Ring bridge",
        "Two clear glass rings with warm cores, joined by a longer amber-gold bridge than a tight pair, the bridge sagging slightly and tack sharp at its lowest point.",
        "A suspension gap between two dark protein towers, the rings hovering near each tower, the bridge crossing the gap.",
        "Amber light from the bridge, towers in silhouette, a faint warm core in each ring. The gap is black. Haze under the bridge.",
        "From below the bridge looking up, shallow depth of field, the low point sharp.",
        "Amber, gold, and black towers, filmic highlight roll-off.",
        "The camera travels under the bridge from one ring toward the other at a constant speed from the first frame to the last.",
        "A gold pulse leaves the first ring, crosses the sagging bridge, and reaches the second ring. Tower edges catch a little amber.",
        "Reach the second ring and start to climb past it.",
        "The climb looks back along the full bridge to the first ring, both towers in frame.",
        "The rings and their amber bridge keep their shapes for the whole shot.",
    ),
    L(
        "Tail channel",
        "A coral glass ribbon with one bright lipid tail, the ribbon coiled once, the tail sticking out of the coil. The tail's root is tack sharp.",
        "A narrow coral-lit channel in dark membrane, just wide enough for the coil, the channel bending out of sight.",
        "Coral light from the ribbon on the channel walls, the tail brighter, the bend beyond black. Haze.",
        "Inside the channel behind the coil, looking toward the bend, shallow depth of field.",
        "Coral, warm white, and dark red-brown walls, filmic highlight roll-off.",
        "The camera follows the coil as it drifts toward the bend at a constant speed from the first frame to the last.",
        "The lipid tail waves, glass spheres in the coil light in a loop, and the channel walls shimmer.",
        "Follow into the bend and keep moving.",
        "Around the bend the channel opens a little, the coiled ribbon and its single tail still ahead.",
        "The ribbon keeps its coral glass and one bright tail for the whole shot.",
    ),
    L(
        "Lantern field",
        "One cyan glass lantern, a tight cluster of spheres with white bonds, tack sharp. Smaller matching lanterns sit farther off and softer, never competing with the near one.",
        "A dark field of low membrane dunes, cyan specks scattered to the horizon, the sky of the cell black.",
        "The near lantern is the key. Distant lanterns are dimmer cyan. Dunes catch faint light on their crests. Deep blacks.",
        "Low among the dunes, the near lantern close, shallow depth of field, horizon soft.",
        "Cyan and black, white bond sparks, filmic highlight roll-off.",
        "The camera moves low and forward toward the near lantern at a constant speed from the first frame to the last.",
        "The near lantern's white bonds flare in a ring, and a faint cyan pulse leaves it across the nearest dune.",
        "Pass the near lantern and continue toward the horizon.",
        "The horizon's smaller lanterns grow slightly, the near lantern now behind and still lit.",
        "The near cluster keeps its cyan glass and white bonds for the whole shot.",
    ),
    L(
        "Gallery climb",
        "A platinum helix seen from inside its own turns, glass spheres large and close, one sphere tack sharp filling a third of the frame, the helix continuing up out of sight.",
        "A tall shaft whose walls are close and paneled with dark rectangles, thin cool lines between panels.",
        "Cool light on the near sphere, silver specular, the panels almost black, a brighter slit far above.",
        "Inside the helix looking up, shallow depth of field, the near sphere sharp, upper turns soft.",
        "Platinum, silver, and panel-black, filmic highlight roll-off.",
        "The camera climbs inside the helix at a constant speed from the first frame to the last.",
        "Spheres pass the lens, each catching a silver flash. Panel lines drift downward.",
        "Keep climbing toward the slit.",
        "The slit brightens and more turns of the platinum helix are still above the camera.",
        "The helix keeps its platinum glass and even turns for the whole shot.",
    ),
    L(
        "Dome ring",
        "A wine-rose ring of glass spheres lying flat, silver bonds, seen from above, one sphere at the near edge tack sharp. The ring is wide in the frame.",
        "A dark floor with a faint circular inlay, the dome above barely visible, a few warm pinlights in the inlay.",
        "Low warm light from the inlay pinlights, the ring glowing wine-rose on its own, the dome lost in black.",
        "Top-down, not perfectly overhead, shallow depth of field on the near sphere.",
        "Wine-rose, silver, and warm pinlights, filmic highlight roll-off.",
        "The camera descends toward the ring and rotates slowly, constant speed from the first frame to the last.",
        "Silver bonds ignite in sequence around the flat ring. Pinlights in the inlay answer.",
        "Level off just above the ring and keep rotating.",
        "The rotation shows the full circle and the dark floor's inlay, the ring unchanged.",
        "The ring keeps its wine-rose glass and silver bonds for the whole shot.",
    ),
    L(
        "Clay fold",
        "Terracotta and gold glass strands in a loose braid that opens at one end, the open end tack sharp, the tight end softer and farther.",
        "A clay-colored fold of membrane like a canyon wall close to the lens, the braid in front of it, the right side of frame open and dark.",
        "Warm rake light from the right, gold strand brighter, terracotta softer, the wall texture readable, the open side black.",
        "Beside the open end, looking back along the braid to the wall, shallow depth of field.",
        "Terracotta, gold, and dark clay, filmic highlight roll-off.",
        "The camera travels from the open end toward the tight end at a constant speed from the first frame to the last.",
        "White flashes hop along the crossings toward the tight end. The wall's texture slides.",
        "Reach the tight end and swing out into the dark side.",
        "The swing shows the whole braid against the clay wall, still one twisted pair.",
        "The braid keeps both strands and their terracotta and gold glass for the whole shot.",
    ),
    L(
        "Shelf seed",
        "A tiny gold glass peptide with a brighter core, sitting on a shelf edge, tack sharp, small against the shelf's thickness.",
        "The edge of one thick organelle shelf, the top surface dim gold, the drop beside it endless and black.",
        "The core is a small warm key. The shelf top takes a weak gold wash. The drop is black. A little haze over the edge.",
        "At shelf level, the peptide near the edge, the drop filling half the frame, shallow depth of field.",
        "Sunlit gold and black, filmic highlight roll-off.",
        "The camera creeps along the shelf toward the peptide at a constant speed from the first frame to the last.",
        "The core pulses, a faint gold ripple runs to the edge, and fine dust lifts off the shelf.",
        "Reach the peptide and ease out over the drop without stopping.",
        "Over the drop, the tiny peptide and the shelf edge are all that remain in the gold light.",
        "The peptide keeps its compact gold shape and brighter core for the whole shot.",
    ),
    L(
        "Green ceiling",
        "A short mint glass chain hanging from a pale green ceiling by nothing visible, simply suspended, the top sphere tack sharp.",
        "A low room, ceiling close, floor a dark pool, the ceiling faintly green and softly lit, a few light bubbles in the air.",
        "Ceiling light, mint on the upper spheres, the lower spheres dimmer, the pool black. Calm haze.",
        "Below the chain looking up, shallow depth of field, top sphere sharp, ceiling soft.",
        "Mint, pale green, and black, filmic highlight roll-off.",
        "The camera rises toward the ceiling along the chain at a constant speed from the first frame to the last.",
        "Spheres brighten from the bottom upward, a green-white flash, and the ceiling's light shivers.",
        "Pass the top sphere and continue into the space under the ceiling.",
        "Under the ceiling the short mint chain hangs below the camera, still straight.",
        "The chain keeps its short mint glass form for the whole shot.",
    ),
    L(
        "Pillar knot",
        "An ocean-teal glass lattice with the dense knot low, almost resting among pillar bases, the knot tack sharp, sticks reaching up into fog.",
        "Pillar bases in fog, the pillars disappearing overhead, the ground dark and wet-looking, teal light pooled low.",
        "Low teal pool light, the knot brightest, pillar bases rim-lit, overhead lost in fog.",
        "Near the ground, the knot large, a pillar base soft at frame right, shallow depth of field.",
        "Ocean teal and dark ground, pale aqua in the fog, filmic highlight roll-off.",
        "The camera rises from the ground up along the sticks at a constant speed from the first frame to the last.",
        "A teal pulse leaves the knot and climbs the sticks into the fog. Pillar bases fall away below.",
        "Keep rising into the fog.",
        "The fog thickens, the sticks still visible, the knot now a teal glow below.",
        "The lattice keeps its teal glass and low dense knot for the whole shot.",
    ),
    L(
        "Plaza dust",
        "A tiny amber-and-gray molecule at the end of a trail of amber dust, the molecule tack sharp.",
        "A vast plaza with a reflective dark floor, distant organelle monuments, and a low amber path of dust across the floor.",
        "The molecule and its dust path are the warm light. Monuments are cool and dim. The plaza edges are black.",
        "Low to the floor, looking along the dust path to the molecule, shallow depth of field.",
        "Amber, cool gray, and blue-black, filmic highlight roll-off.",
        "The camera moves low along the dust path toward the molecule at a constant speed from the first frame to the last.",
        "Dust motes lift and drift to the molecule, amber spheres answering with a small bright ring.",
        "Arrive and rise over the molecule, still moving forward.",
        "Overhead, the dust path, the tiny molecule, and the distant monuments all read in one wide view.",
        "The molecule keeps its tight amber-and-gray packing for the whole shot.",
    ),
]
